### ISSUE TITLE
building the document

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#101]
I made a function to build the document. There are a few files that one will need to download from [data-raw](https://drive.google.com/drive/u/0/folders/1i1RF3cXyWfyQM7d2gK2nYm-BJXpDzwhr) before this will work.
* reccpuewa-results.RData
* Triennial_North_gamma
* Triennial_South_gamma
* WCGBTS_North_gamma
* WCGBTS_South_gamma

then let me know what errors you get when you run
```
load_all()
compile_ling()
```

Disclaimer, if you don't already have the figures in that folder it will take approximately an hour to build, so do not do it in an R window where you are currently working if you want to be able to keep working.

**Comment by kellijohnson-NOAA** [comment]
- [ ] get this working in github actions

**Comment by iantaylor-NOAA** [comment]
I get the following error when compiling. 
I'm happy to wait until ongoing revisions by @kellijohnson-NOAA are complete before trying again.

```
> compile_ling()

processing file: North.Rmd

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |.                                                                     |   1%
   inline R code fragments


  |                                                                            
  |.                                                                     |   2%
label: opts (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 21-69 (North.Rmd) 
Error in gzfile(file) : invalid 'description' argument
```

**Comment by kellijohnson-NOAA** [comment]
missing file, probably one of the analyses that I manually cached. Let's deal with this once the repo is cleaned up.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA try it after downloading [this file and placing it in data-raw](https://drive.google.com/file/d/1fj_uFvf0tKZVEmwcjV3Dg_fs1xz7gxHW/view?usp=sharing)

**Comment by iantaylor-NOAA** [comment]
Sorry, no luck. Same error after downloading that file, running `devtools::load_all()` and trying `compil_ling()` again. 

My only .Rdata files in data-raw are `catch.RData`, `PacFIN.LCOD.bds.30.Apr.2021.RData`, and `reccpuewa-results.RData`. 
I also have `Triennial_North_gamma`, `Triennial_South_gamma`, `WCGBTS_North_gamma`, and `WCGBTS_South_gamma`.

**Comment by kellijohnson-NOAA** [comment]
Okay, [one more](https://drive.google.com/file/d/14cDJAMTH9SpoRBEU_Um5cL_G38P3xVHv/view?usp=sharing).

**Comment by iantaylor-NOAA** [comment]
Additional changes in recent commits from @kellijohnson-NOAA got the document compiling much further than before, but after installing a bunch of latex packages, I got the following error:
```
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: command log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr-commands.log
! Package luatex.def Error: File `Indices_for_Kelli/ORAtSeaCPFVIndex_writeup_fi
les/figure-latex/fig-posterior-mean-ORAtSea-1.pdf' not found: using draft setti
ng.

Error: LaTeX failed to compile North.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See North.log for more info.
```

**Comment by kellijohnson-NOAA** [comment]
ahh, sorry that was so I could add the indices, which there are a few that got included. Download [this folder](https://drive.google.com/drive/folders/1tRdsY_X_SSlNdcSghv5wnCPQRlCYTzLG?usp=sharing) and put it in doc

**Comment by iantaylor-NOAA** [comment]
Success!
Note: it also (or instead) required [ORAtSeaCPFVIndex_writeup_files](https://drive.google.com/drive/folders/1eBNGr2KjQ87NHRRjMnN9W7hCX5MQMfMC) which was in that separate location outside of "Indices_for_Kelli" on Google Drive.

**Comment by kellijohnson-NOAA** [comment]
Thanks for troubleshooting that. I will try to make things more streamlined in the future so it is not such a process to get new machines up and running. Honestly I am not sure what to do about external files b/c our package is already bloated and adding everything would increase that, as well as increase the theoretical run time needed to build it in the cloud. It already takes 35 minutes to build a simple sa4ss document. I can't even imagine how long it would take to install everything here. @ericward-noaa do you know much about github actions and using instances that have things built on them already? For example can we save an install of a few packages that are only available on github that need to be available for an action rather than building them from scratch each time we want to compile a document? Perhaps this is what docker is for, but I am not familiar with docker :(
