### ISSUE TITLE
More info on OR catch reconstruction

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#103]
@aliwhitman noted that the OR section is smaller than WA or CA. This is largely because OR is based on a published paper where CA and WA were my own methods. I do not think that we have to have more text but if you want to provide more @aliwhitman then feel free. You can actually edit the text right here in the web browser by selecting clicking on the file and then at the top next to "Raw" "Blame" there is a pencil icon that will say edit when you hover over it. You can make your edits and then write a little message at the bottom saying you made edits for OR and hit commit to main. Or you can post them to the drive. OR NOT EDIT anything. All options are great. Thanks for READING THE DOCUMENT.

https://github.com/iantaylor-NOAA/Lingcod_2021/blob/26f48baa36768a80b68f1b5b44fdcefcecae9105/doc/catch.Rmd#L889-L901

**Comment by aliwhitman** [comment]
I think this is fine! Thanks Kelli!
