### ISSUE TITLE
assignees not showing everyone

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#104]
@iantaylor-NOAA do you know why I cannot assign an issue to Ali or Melissa Haltuch?

**Comment by iantaylor-NOAA** [comment]
Settings > Manage Access shows me that the invite to collaborate on the repo got filtered to spam or buried in their email. Makes sense that you can't just assign issues to any random github user. Now I also understand why their usernames don't autocomplete when I start typing.

I'll cancel the invitation as invite them again.
