### ISSUE TITLE
comments from @aliwhitman on OR rec comp write up

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#105]
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/006775ddbe9fdb5a112deb3bc33b6b9c5214c491/doc/rec-comps-north.Rmd#L8

@brianlangseth-NOAA Ali noted that the text "values; however, sample size was limited and therefore, imputed lengths were used." should be corrected. She was surprised imputed samples were used. She didn't think sample size would be an issue for lingcod. Can you double check this?

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA That text was pulled directly from the text that @aliwhitman provided [here](https://docs.google.com/document/d/1u5eG7wqw4wc0BG9UIpsa1U-kWOwpNfEq/edit) (not sure if ali gets this). 
All lengths were used in the comps. Sample sizes are below

table(or_mrfss$Length_Flag)
computed measured  missing 
    2455     5912      917

**Comment by kellijohnson-NOAA** [comment]
she is on git and gets the messages we are working on being able to tag her. thanks for the sleuthing.

**Comment by kellijohnson-NOAA** [comment]
@aliwhitman Should we change the following sentence
```
ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values;
however, sample size was limited and therefore, imputed lengths were used.
```
You noted it in the draft document, Brian said it is was copied from text you provided, but he think it might have been a holdover from another assessment.

**Comment by aliwhitman** [comment]
It is a holdover (sorry!), but could just be modified for lingcod to say: 

ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values; however, most imputed weights were conversions from total to fork length, which do not introduce a great deal of uncertainty, and therefore, all lengths were used.
