### ISSUE TITLE
comments from @aliwhitman on management history for rec fishery

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#106]
@aliwhitman noted that in section 1.4.2 Recreational Fishery that "In OR, we have had bag limits for lingcod since 1976. I'll bet WA also had regulations before that as well, but this reads as if there were no recreational regulations before 1994." You mentioned you could write some text. I don't think this is a huge deal if it is not fixed by Monday, but it would be nice to get it flushed out before the final final.

https://github.com/iantaylor-NOAA/Lingcod_2021/blob/cebcf4f660a4d775cc2a578370ee6876dc3295d8/doc/16management.Rmd#L78-L88

You also mentioned you could get the full citation for Rasmuson et al. 2020, but I think I am good. It is showing up in the pdf. So, I am not sure what the comment actual meant.

**Comment by aliwhitman** [comment]
Kelli - it says I need to be on the branch to edit the Rmd. I'd like to revise this one, so please let me know what to do...

**Comment by iantaylor-NOAA** [comment]
@aliwhitman, I get that message too, so they must not allow direct edit of the files on github.com unless you create a branch first. I do see that you now listed as a collaborator so you could clone the repository, edit the file and push the changes using git, but at this stage it's probably quicker and safer to have you just paste the revised text into an this or send it via email.

@kellijohnson-NOAA may have different ideas.

**Comment by aliwhitman** [comment]
I am happy to just paste new text here... I tried to revise it for OR without changing the WA or CA information... so please edit if you need to.  THANK YOU!  I think I would get in trouble at the office if I didn't correct this one :) 

### Recreational fishery

Recreational regulations for `r spp` were established in 1976 in Oregon that included a five fish sub-bag limit for marine species. Bag limits in Oregon were reduced to three fish in 1978 and remained at three until 1999.  Regulations in Washington were established in 1994 and included
a bag limit of three fish. In California,
a bag limit of five fish was implemented in 1994, and
a minimum size limit of 22 inches in Washington and California.
The 22 inch minimum size limit was adopted in Oregon in 1995 and
increased to 24 inches in all three states in 1998.
In 1998, the bag limit in Washington and California dropped to two fish per day.
Oregon followed suite in 1999, and
the two-fish bag limit largely remained coastwide until 2008.
The minimum size limit for California increased in 2000 to 26 inches.
