### ISSUE TITLE
added table of commercial sample sizes by lengths to doc

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#107]
I added just a few more edits to the doc. I wanted to get these two tables in before leaving for a week so did so in 5958259

I also moved my sample size tables to "tables" and out of "doc"  in  cd5db22. 

I think I did it right though if the doc does not render feel free to exclude.

**Comment by kellijohnson-NOAA** [comment]
i will check the build right now. thank you for everything!
