### ISSUE TITLE
Ian's next tasks

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#109]
Here's what I'm working on:
- [x] numbers-at-age tables on the web view (now available at https://iantaylor-noaa.github.io/Lingcod_2021/, although we could better integrate them with other stuff up there in the future)
- [x] add text for empty sections in doc\30model.Rmd
  - [x] north vs south (rough text added in 53f2531a214e64ab83268b35824683cc62b4737d)
  - [x] results
  - [x] sensitivities, profiles, and retros
- [x] projections table
- [ ] finish remaining sensitivity analyses
  - [ ] north
  - [x] south
- [x] north model selectivity changes to model-selectivity.Rmd (also note in model-parameters.Rmd > fixed parameters)
- [x] table of estimated parameters: add Q, remove forecast recdev

Unfortunately I just lost power in my house along with most of the rest of Orcas Island ("Crews responding. No estimate on restoration at this time"), so I'm limited to how long my battery lasts. I'll prioritize writing as that seems more critical and also takes less power than running sensitivities. I guess after that I could write on a piece of paper, but hopefully it won't come to that.

**Comment by iantaylor-NOAA** [comment]
The power just turned back on, but my own energy level is now depleted, so I'm quitting for the night.
@kellijohnson-NOAA, please take a look at [doc/model-north-vs-south.Rmd](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/model-north-vs-south.Rmd) at some point to see if it 
seems balanced enough. Also, excuse the non-dynamic values and inefficient calculations.

**Comment by kellijohnson-NOAA** [comment]
I am reading it right now, but I am having trouble compiling b/c it cannot find the figures listed in figures/figures_compare_north_vs_south ... did you forget to push the .png files?

**Comment by iantaylor-NOAA** [comment]
Sorry about the figures. The png files are there (e.g. https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/figures/compare_north_vs_south_growth.png), but this my first attempt at using a csv with multiple files (https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/figures/figures_compare_north_vs_south.csv) and maybe I brought it in wrong here:
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/8c5b4da572d0d1a42d93c1ced0dc458b3001244c/doc/53figures.Rmd#L297-L304
