### ISSUE TITLE
model sections needed

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#113]
As per dover because @chantelwetzel-noaa and @aaronmberger-nwfsc do such great work
- [x] 3.3 Base Model Results
- [x] 3.3.1 Parameter Estimates [IGT?]
- [x] 3.3.2 Fits to the Data [IGT?]
- [x] 3.3.3 Population Trajectory [IGT?]
- [x] 3.4 Model Diagnostics 
- [x] 3.4.1 Convergence [KFJ?]
- [x] 3.4.2 Sensitivity Analyses [IGT?]
- [x] 3.4.3 Likelihood Profiles [KFJ?]
- [x] 3.4.4 Retrospective Analysis [KFJ?]
- [x] 3.4.5 Historical Analysis (more text added to N vs S)

**Comment by iantaylor-NOAA** [comment]
Placeholders added to 30model.Rmd in e6601123c8b161e4d91711885082277c8e7d3d2e.
We may be able to drop `Historical analysis` by adding some text to `Comparison of north and south models` along with the table added in e10ddd63c525f3450c332b9c62e0ba7ee4726051.

**Comment by kellijohnson-NOAA** [comment]
I think adding historical to the NS comparison is a great idea.
