### ISSUE TITLE
vast residuals by year

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#114]
VAST residuals by year did not plot automatically when running VAST. These will need to be generated for each of the four VAST runs. The code is buried in FishStatsUtils.
- [x] make pearson residual plots
- [x] make a csv for the html
- [x] upload them to the html githubio site

**Comment by kellijohnson-NOAA** [comment]
A ggplot2 version of the residuals for the Triennial
![image](https://user-images.githubusercontent.com/4108564/123587709-866b1700-d79b-11eb-91ee-d9f702cdfe53.png)

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA the vast figures at the resolution that I intended them to be are now in the repository. I am not sure how to best include them in the html. Could you please walk me through this so I do not mess things up.

**Comment by iantaylor-NOAA** [comment]
Thanks for remembering this. I made some progress on writing documenting the html / github.io process here https://github.com/r4ss/r4ss/issues/544 but ran out of time for today. I'll either wrap that up later tonight or work a little tomorrow morning on that and a couple other tasks that I promised this week.

**Comment by kellijohnson-NOAA** [comment]
I can export the data frame to a csv with the caption information if you want. It is made [here](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/R/add_figure_vast.R) but never saved.

**Comment by iantaylor-NOAA** [comment]
VAST residuals are now available in VAST tab at https://iantaylor-noaa.github.io/Lingcod_2021/North/ and https://iantaylor-noaa.github.io/Lingcod_2021/South/ thanks to commit 8a7f434ea6984fc1597838500d0575946d5b55f3 by @kellijohnson-NOAA.
