### ISSUE TITLE
Counts of parameters are off in the text

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#115]
fix parameter count section in document, where the south was two parameters shy of the full number. The north model added up, but that was based on the previous base because i haven't rebuilt it yet.

**Comment by iantaylor-NOAA** [comment]
Fixed in commit 4912781. Here's a snapshot of model-parameters.Rmd rendered outside of the document (where I think the math comes out right).
![image](https://user-images.githubusercontent.com/4992918/123587367-0775de80-d79b-11eb-86b6-43565d8bdf5b.png)
