### ISSUE TITLE
document links

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#116]
documents shared with council staff via https://drive.google.com/drive/folders/1eOu5IX3WmevhBPf_s8zSeXldh-3eph95

a few figures that didn't get into the document are added the respective tabs in the r4ss plots at https://iantaylor-noaa.github.io/Lingcod_2021/

**Comment by andi-stephens-NOAA** [comment]
Did you forget me?  I'm supposed to review, too!

**Comment by aliwhitman** [comment]
Ian, Kelli - just a note - the index folder here doesn't include the two OR indices that are actually in the model... (1) ORBS and (2) nearshore fixed gear logbook.  Not sure if you meant to include those here separately or not.

**Comment by kellijohnson-NOAA** [comment]
can you check that what you want is actually in the document, i included OR but just didn't have time to get all of the CA information in. I will send you a link.

**Comment by aliwhitman** [comment]
I am so sorry guys - I was on kiddo duty this afternoon and didn't get the email notification.  The OR indices ARE included in the main document, and so I am not super concerned that they aren't included separately in the indices folder.
