### ISSUE TITLE
Add sections to the document for considerations and needs

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#123]
```
Regional management considerations and updated (e.g., based on your opinions from this model) research and data needs sections should be included
```
- [x] regional management considerations
- [x] research and data needs
- [ ] read/edit first draft text supplied by @iantaylor-NOAA

**Comment by iantaylor-NOAA** [comment]
First draft text of research and data needs added in commit 34cf8c6 (pasted below).

Lingcod STAT members are welcome to edit https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/research-and-data-needs.Rmd or comment here on any suggestions for changes or additions

![image](https://user-images.githubusercontent.com/4992918/127410810-56a58cde-e861-4868-a92d-7bb0f9cd88b5.png)

**Comment by brianlangseth-NOAA** [comment]
This looks good @iantaylor-NOAA and covers what we had in the note cards for future research in the STAR panel project.
