### ISSUE TITLE
r4ss errors like (plot 1 of 3):

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#124]
Repeating in caption of (plot 1 of 3) (plot 2 of 3) (plot 3 of 3)

**Comment by iantaylor-NOAA** [comment]
I tracked this in r4ss and fixed it in https://github.com/r4ss/r4ss/commit/3b3f849388ca7a1da3d27093e82cc32f951686b9.
Getting the fix into the lingcod repo involved deleting the plots and 00mod.Rdata files within the base model directories and re-running the compile functions.
