### ISSUE TITLE
share some style choices across presentations

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#126]
Using xaringan as a presentation tool has been a pleasure--it's so easy. Thanks @kellijohnson-NOAA for setting that up.

Here are a few changes that I made to the STAR01 presentation in 2e1bf65bf67246f7dc7b756c6de42f590f1692d5 that might be useful for the others:
- reduce the NOAA logo width from 50% to 20%
- add the "fc" theme to bring allow commands like .pull-left-40[] more info here: https://yue-jiang.github.io/xaringan_example/#5
- use `_B_<sub>40%</sub>` instead of inline equation `$B_{25\%}$` to get better formatting as shown bullet 2 vs 3 in the slide below
![image](https://user-images.githubusercontent.com/4992918/124823864-85b64b80-df26-11eb-9006-af4154687f9c.png)

**Comment by kellijohnson-NOAA** [comment]
Do you just not like bullet 3 b/c it is bold? I am fine with using the simpler notation for these presentations and I don't think anyone will notice that it is not in actual math mode. But for long-term purposes it would be more "accessible" to use math mode because it is commonly read by screen readers.

**Comment by iantaylor-NOAA** [comment]
Yes, I found the bold to be distracting, but the accessibility point is enough to convince me to switch back (which is also easier for copying text from elsewhere in the doc).

**Comment by kellijohnson-NOAA** [comment]
It must be a font thing because equations are not actually bolded. You could try removing the fonts that I set at the top or trying a different font because the equations in [this example](https://garthtarr.github.io/sydney_xaringan/#47) don't look different.
