### ISSUE TITLE
STAR review action items: Day 1

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#130]
List of action items from each day of the STAR panel. Individual tasks are given own issue

- [ ] start listing items here

**Comment by iantaylor-NOAA** [comment]
I made this Google Doc as a place to share notes within the lingcod STAT if it would be useful
https://docs.google.com/document/d/1Y6QFvU_dOaoK4n0KS1jXc_ID8YY3aFlHUa-1O05Sp8w/edit
we also have this GitHub Project: https://github.com/iantaylor-NOAA/Lingcod_2021/projects/4.

**Comment by brianlangseth-NOAA** [comment]
We are adding new issues for requests as they go. No need to keep this one.
