### ISSUE TITLE
Day 1 task - Compare results with Oregon ROV data

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#132]
Unsure if this is for the STAR panel or best to include after in the report (see #129)

Oregon has ROV data from the MPAs that we did not include in the model or report. Omitting from the model is sensible, but should include in the report, if it is not already.

**Comment by aliwhitman** [comment]
so we do have ROV data for lingcod but did not have the time to work it up as we did with quillback.  Some data are from inside our reserves and some data are outside reserves. We were limited by the ROV project leader's time (internal to ODFW).  It should certainly be mentioned as an additional source of fishery-independent information that could be explored in the next assessment.  I could write something up regarding this for final report if we want. Just let me know if we do... 

We do have data from the hook and line surveys in the Oregon marine reserves and the video lander population estimate already in the assessment document (but as you noted, not in the model).

**Comment by brianlangseth-NOAA** [comment]
Going back through notes the text there says "Why did we not use the rover data from Oregon that collects samples from the MPAs." so it may not be focused on ROV data but rather why wasn't the material we already have in the assessment (hook and line, and video) not used in the model itself.  Note have justification and we could potential add text in the report to make it more clear. 

@aliwhitman Thank you for offering, I dont think we need a write up of data not yet available for inclusion. If we do we will let you know.
