### ISSUE TITLE
Day 1 task - post updated presentation 3

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#134]

**Comment by iantaylor-NOAA** [comment]
The updated presentation was posted by Todd to the FTP site shortly after the meeting: ftp://ftp.pcouncil.org/pub/!2021%20GF%20STAR2_Lingcod/Presentations/
but thanks to this issue I just replaced the version on Google Drive as well: https://drive.google.com/drive/folders/1r8EHoQTeXkxfn77zbwzY7_F_Aj_4HYwJ
