### ISSUE TITLE
Day 1 task - Selectivity figures for when M = 0.3

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#135]
The figure in Slide 28 of version 2 of presentation 3

**Comment by iantaylor-NOAA** [comment]
This didn't end up becoming a formal request but there's no extra effort to provide the figs if needed. 

They are `sel01_comm_fleets.png` and `sel01_noncomm_fleets.png` (no accompanying csv file) 
just pushed along with other model files to [models/2021.n.022.405_female_sel_offset_M0.3](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/2021.n.022.405_female_sel_offset_M0.3/) and [models/2021.s.014.405_female_sel_offset_M0.3](https://github.com/iantaylor-NOAA/Lingcod_2021/tree/main/models/2021.s.014.405_female_sel_offset_M0.3)

Results are pretty similar to the sensitivity without M fixed at 0.3 (here for the south only):
![sel01_comm_fleets](https://user-images.githubusercontent.com/4992918/125387178-59e5fc00-e352-11eb-86df-23cb4497d07a.png)
![sel01_noncomm_fleets](https://user-images.githubusercontent.com/4992918/125387180-5a7e9280-e352-11eb-9f60-cb1659f2fd0b.png)
