### ISSUE TITLE
Day 1 task - Resolve Theresa's concern about text for discards

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#136]
Confusion about how WA discards are written in the report. Possibly move to (#129) but for now we should understand what Theresa's concern is, and how to remedy.

**Comment by iantaylor-NOAA** [comment]
Text is on page 13 under 2.1.2.2 Washington recreational landings.
- [ ] revise paragraph to reflect that catch time series for WA rec includes dead discards
- [ ] revise caption for figure 11 to reflect that the WA catch in the old model 
- [ ] maybe add a figure like the following which compares the time series of inputs from each year to the catch in the same units  as calculated within the model based on the input in other units (committed as `figures/WA_rec_catch_comparison.png`, created by `data-raw/WA_rec_catch_comparison.R`, in 5e5766b).
![WA_rec_catch_comparison](https://user-images.githubusercontent.com/4992918/125490067-d942a5eb-533b-44b1-a6b6-be5b5a98ed9e.png)

**Comment by kellijohnson-NOAA** [comment]
I didn't add the figure but I did the other two tasks.
