### ISSUE TITLE
make more use of sens_make_table() and table_sens()

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#147]
The function `sens_make_table()` (defined in the file https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/R/sensitivity_output.R)
can be used to create a table like those for the document and sensitivity analyses.

The following command
```
  # make 'comp' sens table for STAR day 2 request 3 (no fishery ages + DM)
  sens_make_table(
    area = "n",
    num = 22,
    sens_base = 1,
    sens_nums = c(204,208,209),
    sens_type = "comp_STAR_day2_request3",
    write = TRUE
  )
```
creates a time-series figure:
`models/2021.n.022.001_new_INIT/custom_plots/sens_timeseries_n_comp_STAR_day2_request3.png`
and a table
`tables/sens_table_n_comp_STAR_day2_request3.csv`
where those filenames depend on `sens_type` input.

These can then be used in a presentation via code like that used here, including calling `table_sens()`:
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/presentations/star_2_responses.rmd#L152-L183

If you want to compare models that differ in the `num` value, not just the `sens` values, at this stage it would probably be easiest to just renumber the model files.

**Comment by iantaylor-NOAA** [comment]
Change to `sens_make_table()` in commit eefc7c9 adds steepness to the table of parameters (replacing log(R0) which is redundant with the unfished recruitment also reported).

**Comment by kellijohnson-NOAA** [comment]
Here is another example for "non-sensitivity" runs where you just want to look at random models.
```
compare_table <- sens_make_table(
  area = "s",
  sens_mods = list(mod.2021.s.017.001, mod.2021.s.017.810),
  sens_type = "random",
  plot = TRUE,
  plot_dir = newdir,
  table_dir = newdir,
  write = TRUE
)
```
@brianlangseth-NOAA you could use this to compare the base model to a run with new discard information. Just change sens_mods to results of SS_output or get_mod and give it a directory instead of newdir.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA what do you think about changing the function to make all of the comparison plots rather than just a single one?

**Comment by iantaylor-NOAA** [comment]
That's a great idea. Go for it if you wish.

**Comment by iantaylor-NOAA** [comment]
In commit 8a282587ef541e4bd8fb27efb1b4beb04e7bb44b I revised the `sens_make_table()` and `table_sens()` functions so that you can now provide a `sens_names` input to the first function to provide model names used in the figure legend and table headers. Using `pretty = FALSE` in `table_sens()` makes use of `utils::read.csv(..., check.names = FALSE)` and skips running the internal `prettynames()` function.

I also just changed "Survey" to "Indices" in the labels of likelihood types after getting tired of explaining that it also included likelihoods from fishery-dependent indices.

Example use is below:
```
# create table of model comparisons for some lingcod models
newdir <- 'figures/STAR_request20'
dir.create(newdir)
compare_table <- sens_make_table(
  area = "n",
  num = 23,
  sens_mods = list(mod.2021.n.023.001,
                   mod.2021.n.023.204,
                   mod.2021.n.023.420,
                   mod.2021.n.023.003),
  sens_names = c("North base model",
                 "High state (no fishery ages)",
                 "Low state A (sex-sel)",
                 "Low state B (M = 0.3)"),
  sens_type = "random",
  plot = TRUE,
  plot_dir = newdir,
  table_dir = newdir,
  write = TRUE,
  )
```

```
<!-- add table of model results without changing the column headers) -->
`r table_sens("../figures/STAR_request20/sens_table_n_random.csv", 
              caption = "", format = "html", pretty = FALSE) %>%
      kableExtra::kable_styling(font_size = 12) 
```
![image](https://user-images.githubusercontent.com/4992918/125892565-e95f6849-c05b-4902-80ac-e26b71162b64.png)
