### ISSUE TITLE
create decision tables

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#154]
We still need to choose final models and then states of nature, but when it comes to decision-table creation, here's the messy code I used for the Big Skate assessment in 2019.
https://github.com/iantaylor-NOAA/BigSkate_Doc/blob/master/R/BigSkate_decision_table_stuff.R

r4ss functions available include `SS_ForeCatch()` to get the HCR catch from the base model in the format required by the forecast.ss as fixed catches for the low and high states of nature:
```
SS_ForeCatch(bs99, yrs=2019:2030, average = TRUE,
             avg.yrs = 2017:2018, dead=TRUE, digits=1,
             total = c(rep(241.3, 2), rep(250, 10)))
```

There is also a non-exported function `SS_decision_table_stuff()` which can be useful to fill in the table itself:
```
### extract values from time-series
# note that SS_decision_table_stuff isn't exported to NAMESPACE so requires the
# trip colon ":::" to call even if r4ss package is loaded.
vals.base_state_default <- r4ss:::SS_decision_table_stuff(base_state_default, yrs=2019:2030)
vals.base_state_250t    <- r4ss:::SS_decision_table_stuff(base_state_250t,    yrs=2019:2030)
vals.base_state_494t    <- r4ss:::SS_decision_table_stuff(base_state_494t, yrs=2019:2030)
```

**Comment by brianlangseth-NOAA** [comment]
Is this for after the STAR or during? Forgive my ignorance on process.

**Comment by kellijohnson-NOAA** [comment]
[Dover example](https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/master/code/dover_decision_tables.R)
[ahart's decision table package](https://github.com/ahart1/decisiontable)
[DFO herring decision tables](https://github.com/pbs-assess/herringutils/blob/3b2338cbfa60a1b82b9f48902d04b6bb0670372a/R/tables.R#L231-L572)
[DFO Pacific Cod decision table](https://github.com/pbs-assess/pacific-cod-2018/blob/bddc9192c8e18ebd14c0e9d378047ac4cd127a70/R/tables-decisions.R)

Here is a screen shot of the 2017 decision table
![image](https://user-images.githubusercontent.com/4108564/125798552-7309b33b-3b63-4025-997b-a78b5010c130.png)

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA it is on the agenda for tomorrow, so we should in theory produce them tonight.

**Comment by iantaylor-NOAA** [comment]
Forecast files revised in commit 7a7602a to incorporate the time-varying buffer associated with the default Pstar sigma of 1.0 associated with category 2 stocks.
I'm running models with those forecast now with the thought that these may provide a catch stream for a future decision table.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA Is SPR buffer of 0.45 and First year for caps of 2040 accurate? Seems like 0.5 and 2023 is typical

Ive added some explorations to obtain a fleet breakdown of catch given 2021 and 2022 values in 360609b587931f2c00b27b3a451692b03d2dc7e1. Maybe its useful.

**Comment by iantaylor-NOAA** [comment]
@brianlangseth-NOAA, thanks for looking things over. The SPR target is a council choice. I don't remember if we just retained it from the previous assessments (just checked that they indeed used 0.45) or if we got specific guidance that this was the target. Either way we can confirm tomorrow. 
I don't really understand how the caps and allocations work in Stock Synthesis. I think that it's a tool to allocate among fleets or fleet groups but we always seem to do that outside the model. Putting the first year for caps and allocations beyond the range of the forecast avoids getting a warning about caps and allocations for the models with fixed forecast catches. But we could check that it indeed doesn't have any impact.

The current forecast files use an arbitrary (but commonly assumed) 5-year average of catch with the trawl to fixed-gear amounts re-apportioned to have a 40:60 split (that part requested by the GMT):
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/65da5effb437581a1a594485193beec0a0cfef3f/models/lingcod_forecast.R#L56-L62

We should check that the numbers your script provides are similar to those averaged by the `r4ss::SS_ForeCatch()`. The settings in `lingcod_forecast.R` are right now using total dead catch rather than landed catch as the basis for the forecast but it's worth discussing whether that's the right choice.
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/65da5effb437581a1a594485193beec0a0cfef3f/models/2021.n.023.010_forecast/forecast.ss#L57-L67

**Comment by iantaylor-NOAA** [comment]
I made a start on code in [models/model_decision_tables.R](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/model_decision_tables.R) added in 3236ac9 which

- copies model files for alternative states to new directories
- gets forecast ACL catch values from base model using default HCR (or whatever is implemented in forecast file)
- inputs those fleet-specific catches as fixed values in the low and high states of nature
- re-runs the low and high states using the .par file without further estimation
- extracts the time series of catch, SSB, and fraction unfished from each state

What it does not yet do:
- automatically add rows to models/README.md for the new directories (not sure if this makes sense or not)
- check to confirm that the catch coming out matches across states within a catch stream (in this case, as noted in #163, the low states crash and the catch can't be fully removed--not sure how best to note that in a decision table if we stick with these low states)
- filters the columns to get just those required for the table
- use kable or otherwise make the table ready for inclusion in a document
- repeat the above for the south or any other model
- repeat the above for an alternative catch stream

I'm quitting for the night but I think we're in a good place for tomorrow.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, files decision_table.tex have been added to base model directories for north and south in 4ee9f06. 
I have not tested compiling these into a document. 

The values in these tables differ slightly from those shared previously due to the change in HCR from option 1 to 3 based on input from @chantelwetzel-NOAA ("We as a group should only be using option 3, buffer on catch") see also https://github.com/nmfs-stock-synthesis/ss-documentation/issues/50.

**Comment by kellijohnson-NOAA** [comment]
Decision tables are in the document.
