### ISSUE TITLE
STAR Panel Request #14 (treatment of trawl discards in north model)

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#155]
### Request:

Investigate the discrepancies in catches between the GEMM reports and the northern
model estimates. Explore modeling methods to attempt to improve the fit to the dead
discard rates in the model to produce dead discard estimates that are more in line
with the GEMM values. This adjustment would consider these earlier years (1998-
2001) as well. This investigation should focus on the trawl fleet.

### Rationale:

There are large discrepancies in catches between the GEMM reports and the model
estimates. WCGOP discard rates in the model are from the same data that produce the GEMM
estimates, hence we would expect the model estimates to have coherence with the GEMM
estimates.

**Comment by kellijohnson-NOAA** [comment]
r4ss::SSMethod.TA1.8(mod.2021.n.023.001,type="len",fleet=1,part=2)[1] /
r4ss::SSMethod.TA1.8(mod.2021.n.023.001,type="len",fleet=1,part=1)[1]
=
0.1145

Estimated sample size multiplier for just the discard compositions / Estimated sample size multiplier for just the retained compositions = 0.1145. Thus, the discard composition input sample size will be downscaled by 0.1145 so that the model can focus on fitting the retained catch compositions more so than the discard compositions. That is, for an original input sample size of ten this method would retain the sample size of ten for the retained compositions and make a new input sample size of ~1 for the discarded compositions tricking the model to believe that they contain less information.

**Comment by iantaylor-NOAA** [comment]
The values accidentally got reversed when transcribing from my messy work. It should be partition 1 (discards) relative to partition 2 (retained), which gives: 
```
> r4ss::SSMethod.TA1.8(mod.2021.n.023.001,type="len",fleet=1,part=1)[1] / 
  r4ss::SSMethod.TA1.8(mod.2021.n.023.001,type="len",fleet=1,part=2)[1]
        w 
0.1445044 
```

**Comment by iantaylor-NOAA** [comment]
@brianlangseth-NOAA, I hit the green button too soon on the previous comment. If you've already run the model with the 0.1145 value, let's look at the results before even thinking about redoing anything.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA I haven't yet done that. I will run with 0.14. Appreciate the detailed description @kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment]
Oops that was my fault, I mixed up the partitions.

**Comment by brianlangseth-NOAA** [comment]
Models are up on the drive

2021.n.023.902_discard_se: 
     set discard rates se to 0 (much closer to discard rates from GEMM but some gradient and 1 bound issue)
2021.n.023.903_discard_trawl_rates_se: 
     set discard rates se to values from OB_DisRatios_boot_ncs....csv (slightly worse than 902 but no gradient or bound issues) 
2021.n.023.904_sample size
      reduce discard length sample size by 0.14 (more discards. Seem to have shifted retention left)

Discard rates for bottomtrawl were very similar to what was already there, so didn't run (sens 901)

Im off to bed, and will upload presentation material tomorrow.

**Comment by brianlangseth-NOAA** [comment]
Panel agreed to incorporate this information as a sensitivity. Overall effect on model trajectory is minimal

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA do you think we should keep this open so we are reminded to include the code into the sensitivity function that @iantaylor-NOAA uses to run models or until we get the information into the document.

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA Good question. Im happy to leave open, but wanted to clear our project board. Referencing the sensitivity wishlist (#43) will also help us remember.

**Comment by kellijohnson-NOAA** [comment]
We can just assign it to a new project.

**Comment by iantaylor-NOAA** [comment]
Moved to "[Complete lingcod 2021 assessment document](https://github.com/iantaylor-NOAA/Lingcod_2021/projects/3#card-65096436)".
