### ISSUE TITLE
STAR 2017 recommendation 2: include more info from Canada and Mexico

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#16]
Specific recommendations for the next lingcod assessment from 2017 STAR Report:
> 2. Available information on lingcod catches, abundance trends, and age-compositions should be acquired from Canadian and Mexican authorities to take an initial step towards a more spatially-comprehensive view of lingcod population trends and dynamics.

**Comment by kellijohnson-NOAA** [comment]
I emailed the contact we have for south of the US-Mexico border and I will update when I receive a response.

**Comment by iantaylor-NOAA** [comment]
RecFIN couldn't filter catches from Mexico in 2017 but hopefully could be used to do so in 2021.
We can look at summary documents from Canada to see what recent trends in catch or abundance look like.

**Comment by iantaylor-NOAA** [comment]
Additional information on Lingcod in Canada: 

- the most recent BC Lingcod stock assessment is from 2011: https://waves-vagues.dfo-mpo.gc.ca/Library/344977.pdf. 
- TSC report (https://www.psmfc.org/tsc-drafts/2019/DFO_2019_TSC_Report_Draft.pdf, item K.2. on page 35) notes that "Outside Lingcod were scheduled to be assessed in the spring of 2019; however, the assessment has been pushed back due to other program demands as well as the desire to have some age-data to inform the catchability of the longline surveys"
- @kellijohnson-NOAA exchanged emails with DFO staff who said covid impacted their lingcod ageing and they will not be doing an update to the assessment any time soon, but it is on their to do list
- Anderson et al. 2019 summary (2-page lingcod extract and full report in [references on Google Drive](https://drive.google.com/drive/u/0/folders/1tY7PJtrF01um5oLFxQMQC0z4L-B_Lmdq)) show conflicting information in trends in abundance with trawl surveys trending upward in northern BC, flat in southern BC, and trawl cpue trending down as copied below:
![image](https://user-images.githubusercontent.com/4992918/113052340-dd8d2b80-915b-11eb-9323-90abe74f004d.png)

**Comment by brianlangseth-NOAA** [comment]
The number of samples from Mexico in the recfin bio data is 145, out of ~250,000. Not much to say based on that.

**Comment by iantaylor-NOAA** [comment]
Text in https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/17foreign.Rmd seems to cover this well.
Thanks @hmorzaria for the information on lingcod in Mexico!
