### ISSUE TITLE
First paragraph of data section

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#171]
In the 2021 lingcod assessment documents we tried to document data sets that were used in the base model, explored in sensitivities but not in the base model, explored but not used in any model, and known about but not even explored. We could of for sure done a better job providing rationale on why each data set was explored to the extent that it was. Nevertheless, given the current level of information in the document and the exclusion of "standard" data from the base model there was some angst about data sources being used in the future or the validity of collection methods for data that were not used in the base model. I think some of this stemmed from including information in the document on data sets that were barely explored, which was not done in the past for lingcod. I am thinking that a better introduction to the data section could help reduce concern. The first paragraph of the data section currently reads

https://github.com/iantaylor-NOAA/Lingcod_2021/blob/4ee9f06bec66f1691c2bd55adf25a8fe7d62c73f/doc/20data.Rmd#L3-L5

I am soliciting help for some boilerplate text that we can add to all assessment documents at the beginning of the data section that sets the stage for the potential for not including all data sets and an explanation of how that doesn't mean the data will not be included in future assessments or that it is not worthy of inclusion.

@chantelwetzel-noaa, @shcaba, and @aaronmberger-nwfsc I am tagging you because you are outside of this repo and may have ideas.

**Comment by aaronmberger-nwfsc** [comment]
Here is a start:

Data are the foundational components of stock assessment models.  The decision to include or exclude particular data sources in an assessment model depends on many factors.  These often include, but are not limited to, the specific variable(s) or thing(s) being measured; the way in which data were collected (e.g., measurement method and consistency); the spatial and temporal coverage of the data; the quantity of data per desired sampling unit; and the representativeness of the data to inform the modeled processes of importance.  Attributes associated with a data source can change through time, as can the applicability of the data source when different modeling approaches are explored (e.g., stock structure or time-varying processes).  Therefore, the specific data sources included or excluded from this assessment should not necessarily constrain the selection of data sources applicable to future stock assessments for **\species**. 

Some data sources were not included in the **\species** base model.  These data sources were explicitly explored during the development of this stock assessment, or were deemed sufficiently explored in previous **\species** stock assessments. In some cases, the inclusion of excluded data sources were explored through sensitivity analyses.  Descriptions of each data source included in the model (Figure \@ref(fig:data-plot)) and sources that were explored but not included in the base model are provided below.

**Comment by chantelwetzel-noaa** [comment]
As always, Aaron hits all the points I described but does it better.  I think his paragraphs should be the starting point for additional minor edits.

**Comment by aaronmberger-nwfsc** [comment]
Nice @chantelwetzel-noaa!  I think we can combine these and we have a really good start.

**Comment by shcaba** [comment]
This is a terrific idea, and a great start already.
One thing I plan on doing once out of the assessment Thunderdome is get a spreadsheet of every groundfish in the FMP (rows) and list every data source ever used or could be used for each state/area.
This will allow us to do a check when we have an assigned stock to see what data sources we are expecting to consider. With that, we could then make sure we have some default text for each of those data types as y'all are suggesting here. Hopefully that will complete this circle and give us a major leg up on any groundfish we could consider in the future.

**Comment by kellijohnson-NOAA** [comment]
Brilliant!

Questions that I have

(1) Can we be more specific than "thing(s)" in the following
```
or things(s) being measured
```
(2) Should this
```
included or excluded from this assessment
```
be assessment or base model?
(3) Others that have suggested text please contribute by end of day tomorrow (2021-07-28) and I will combine everything. This version will be used for the lingcod assessment and added to sa4ss. It doesn't mean that it is final or cannot be edited later, just what will be used for lingcod.

Thanks for helping!

WRT @shcaba great idea on a database of potential data. I think we should think about how and where to store this so that stakeholders can have access as well as assessment authors. Would you be willing to draft up a template for the structure that you are thinking and maybe we can discuss it a team meeting?

**Comment by aaronmberger-nwfsc** [comment]
(1) Maybe it should just say "data" instead of 'variable(s)' and 'thing(s)' - I was trying to say what data usually is but it can be of so many forms.  I don't see a need to be super specific.
(2) I was thinking 'assessment' so that the inclusion/exclusion applies to the aforementioned statement about use in sensitivity analyses (even though not in base model still 'included' in assessment document); but either would probably work just fine.

**Comment by brianlangseth-NOAA** [comment]
@schaba, Id like to help out with this spreadsheet to rule all others, as Ive also had this idea.

@kellijohnson-NOAA , as a start we could say 
```
the specific variable(s) or ~thing(s)~ process(es) being measured (e.g. growth, selectivity, trends in the population trajectory)
```

Based on our experience with the data moderate assessments, assuming these continue to be used in the future, I would also like to add to the list of things included in the sentence of  "These often include, but are not limited to, ...." 
```
limitations imposed by the Terms of References, or timing of when the data were provided.
```

**Comment by aliwhitman** [comment]
@brianlangseth-NOAA  is that a Lord of the Rings reference?? 

I can also help with the spreadsheet.  If assessments continue to be conducted along state lines, there will be lots of smaller, state specific datasets that could be brought forward.

**Comment by shcaba** [comment]
I can start a spreadsheet and then share with all interested parties so we can build this out. This will definitely need both state and federal folks fleshing it out. Same goes for the text associated with each data source. Ali did a great job of starting that for some of the Oregon sources. I am sure we can pull from this year's assessments to add to the already great start above. I recall writing up a lot of esoteric data sources for cabezon years ago, so we could pull from there as well. I am sure Melissa Monk has some excellent stuff for several California sources.

**Comment by kellijohnson-NOAA** [comment]
Data spreadsheet is in google drive [here](https://docs.google.com/spreadsheets/d/1w4tO8aqrNYt0JV1E428mv8FCTEB1vm4k21-rh9z5unk/edit?usp=sharing) and will be discussed at [PEP team meeting](https://docs.google.com/document/d/1NkVBe6JIRH53K0x-qpKebh2BPxJp6lqNozT9P7AjOI4/edit).
