### ISSUE TITLE
STAR panel tasks to onboarding or doc

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#172]
@brianlangseth-NOAA can you move cards from the [STAR Panel tasks](https://github.com/iantaylor-NOAA/Lingcod_2021/projects/4) board to the 2 remaining project boards or the Done category so we close this project out?

**Comment by brianlangseth-NOAA** [comment]
Done @kellijohnson-NOAA. Many of the notes were placeholders and specifically focused on things to circle back to during the review. As the review is now done, so are the notes, though we didn't necessarily circle back to all.

**Comment by kellijohnson-NOAA** [comment]
Thanks @brianlangseth-NOAA.
