### ISSUE TITLE
document - describe the model results more

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#181]
John Field noted that ...
```
Section 3.2.5- base model results- there is no description of the actual results,
e.g., trends over time, reference to the figures that show SSB, depletion, recruitment, etc.
A bit of text and reference to the figures would be appropriate.
Tables 16-21 provide most of the information but neither these nor the corresponding figures (Figures 147-156) are referred to in the text.
```

**Comment by iantaylor-NOAA** [comment]
Model results sections on "Parameter estimates" and "Population trajectory" were commented out by me during crunch time with a note `<!-- running out of time -->`, but have now been filled in with some basic text in commit 63546379f4b0780493128db0dc6296e62d291c07 (screenshots below from the south doc).
@kellijohnson-NOAA, feel free to add subtract or modify as you wish.

![image](https://user-images.githubusercontent.com/4992918/141009557-3e9ca3e4-b36d-4c9a-a352-c7d93c7ae6f5.png)
...
![image](https://user-images.githubusercontent.com/4992918/141009589-6bc36c30-5893-4b70-a35e-4bf8f6cfae42.png)
