### ISSUE TITLE
missing files required to compile doc

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#186]
@kellijohnson-NOAA, I've been commenting the following lines to get the doc to compile. Can you either add the associated files or point me to where to get them from Google Drive?

from: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/52tables.Rmd#L332
```
sa4ss::read_child(file.path(paste0(params$model, "_retro"), "mohnsrho.tex"))
```

from: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/53figures.Rmd#L371-L373
```
add_figure_profile(params$model, "NatM", "like_1")
add_figure_profile(params$model, "steep")
add_figure_profile(params$model, "R0")
```

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I committed what I think you need. Let me know if something still isn't working, otherwise feel free to close if you can compile.

**Comment by iantaylor-NOAA** [comment]
Files working fine, thank you @kellijohnson-NOAA
