### ISSUE TITLE
Collect Lingcod Bibtex entries

### ISSUE THREAD

**Issue by andi-stephens-NOAA** [iantaylor-NOAA/Lingcod_2021#2]
- [x] Get Bibtex entries for all citations.
- [x] Stop citing documents that don't exist.

**Comment by andi-stephens-NOAA** [comment]
Up to date as of this commit:  24b1ec0f952345f868b1aaa68e23ef4d1b887d9c

**Comment by iantaylor-NOAA** [comment]
@andi-stephens-NOAA, could you add the 2017 lingcod assessment report to the bib file so that it can be cited in new text as we write it?

**Comment by andi-stephens-NOAA** [comment]
2017 added.  Key is:  haltuch2017lingcod

**Comment by kellijohnson-NOAA** [comment]
Thanks @andi-stephens-NOAA for doing this, the file has been really helpful.
