### ISSUE TITLE
DATA 4 Discard Data

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#22]
Issues listed in the [data spreadsheet](https://docs.google.com/spreadsheets/d/1p3yUKVccYJoY085syAdDRH-pDkN8_WTc/edit#gid=845715953) for determining discard information [plus additional edits from Ian on 5 April 2021]
- [x] Total mortality estimates
- [x] Commercial discard mortality rates--we will probably roll over the 2017 values: "Discard mortality rates of 7% for fixed gears and 50% for trawl gears are applied in this assessment." (from page 43)
- [x] Commercial discard rates from WCGOP
- [x] Commercial length comps from WCGOP
- [x] ~Recreational length comps~ (decided not to model rec discards explicitly)
- [x] ~Recreational discard rates and mortality (see https://github.com/nwfsc-assess/recFIN/issues/2)~

**Comment by iantaylor-NOAA** [comment]
More on commercial discard rates for Lingcod: 

- Commercial discard rates can be processed following the approach @chantelwetzel-noaa used for Dover
  - Description is "A single discard rate was calculated by weighting discard rates based on the commercial landings by each sector" (from https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/master/write_up/21f-.Rmd#L34)
  - Code used to combine across sectors https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/master/code/discard_rates_combine.R

Exploration of sector-specific discard rates for Lingcod are in this script, along with code to make figures like those below (also in [discards](https://github.com/iantaylor-NOAA/Lingcod_2021/tree/main/figures/discards)), which are confidential for some other sectors: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/R/lingcod_discard_ratios.R


![discard_ratios_bottomtrawl](https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/figures/discards/discard_ratios_bottomtrawl.png)
![discard_ratios_NCS_fixed-gear](https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/figures/discards/discard_ratios_NCS_fixed-gear.png)
![discard_ratios_NCS_hook-and-line](https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/figures/discards/discard_ratios_NCS_hook-and-line.png)

**Comment by iantaylor-NOAA** [comment]
No total mortality estimates included, but closing issue anyway.
