### ISSUE TITLE
DATA 5 Biology

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#23]
Issues listed in the [data spreadsheet](https://docs.google.com/spreadsheets/d/1p3yUKVccYJoY085syAdDRH-pDkN8_WTc/edit#gid=845715953) for biology
- [x] Natural Mortality (see issue #40)
- [x] Fecundity (maybe just stick with proportional to weight (comment below)
- [x] Length-weight: estimates from survey sources (WCGBTS, Triennial, Hook and Line) provided e1fcb876e4a6f4a99561b16c943a5438fe74cc09
- [x] Length-age: estimates from survey sources (WCGBTS, Triennial, Hook and Line) provided e1fcb876e4a6f4a99561b16c943a5438fe74cc09
- [x] Age error	(see issue #33)

Also 
- [x] Maturity (new values provided by Melissa Head over email - see values in comment below)

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA we should think about the Hamel prior on M or how we plan treating M.

Is anyone working on fecundity?

**Comment by iantaylor-NOAA** [comment]
Good questions. Here's some info from the 2017 report:

**Fecundity** (page 40)
> Fecundity was assumed to be proportional to weight. Hart (1967) found fecundity to be essentially proportional to length cubed.

Unless @LaurelLam-NOAA is aware of any recent research, I'm happy to stick with that common assumption for non-rockfish species on this coast.

**Natural mortality**
My response here got way too long so I created issue #40 to cover refinement of the prior. I'll edit the initial comment on this issue to point to other issues like this one that are related.

**Comment by LaurelLam-NOAA** [comment]
Ian, 
I do not know of any updates to lingcod fecundity. Melissa Head's recent work is only on histology and maturity so Hart (1967) it is! Though I'm sure it's changed by now..

**Comment by brianlangseth-NOAA** [comment]
Per email from Melissa Head on 5/17/21. Provided biological and function maturity. 

FUNCTIONAL maturity 

North of 40`10: 
L50 = 56.65 cm
slope = -0.279

South of 40`10:
L50 = 51.57 cm
slope = -0.207

**Comment by iantaylor-NOAA** [comment]
@brianlangseth-NOAA and @kellijohnson-NOAA can you help me choose length-weight parameters to put in the control files for each model? I think it makes sense to choose a separate values for each sex within each model. Does that narrow it down to the following 4 sets 
- North_NWFSC.Combo_F
- North_NWFSC.Combo_M
- South_NWFSC.Combo_F
- South_NWFSC.Combo_M

out of this longer list?:

- all
- all_F
- all_M
- all_U
- North
- North_NWFSC.Combo
- North_NWFSC.Combo_F
- North_NWFSC.Combo_M
- North_NWFSC.Combo_U
- NWFSC.Combo
- NWFSC.Combo_F
- NWFSC.Combo_M
- NWFSC.Combo_U
- South
- South_NWFSC.Combo
- South_NWFSC.Combo_F
- South_NWFSC.Combo_M
- South_NWFSC.Combo_U


Also, I see there were some figures made in https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/data-raw/survey_biological_exploration_estimation.R but I don't see them in `figures` so assume they got lost in the reorganization of the package files.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA. You are correct. Use the four sets you've identified.

**Comment by brianlangseth-NOAA** [comment]
The file survey_biological_exploration_estimation.R is an exploratory file. Its the early version of the operational file lingcod_LW_LA, which is meant to be used to obtain LW and LA relationships. I will update those exploratory plots into the figures folder. I will make it clear those plots are exploratory by adjusting names.

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA sorry that I didn't move the figures. Also, feel free to make a directory in Figures and move them there if they won't be used for later documents or presentations but they are helpful for exploration. Or rename them, either is fine.

**Comment by brianlangseth-NOAA** [comment]
No worries @kellijohnson-NOAA. I dont know if I even put them up on the drive. My directory in the file is a local one on my desktop. I like your extra folder idea, and will do that one.

**Comment by kellijohnson-NOAA** [comment]
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/a29c42c2fed1aa029089847f0afd6199e80c73e2/doc/22biology.Rmd#L53
We note that there is a potential to get figures from Melissa Head regarding maturity. @iantaylor-NOAA do you have a figure, I cannot find any in the email labeled "Lingcod maturity results" from Melissa. If we want to ask for a figure, today is the day! I could not find a user name on github for her. So we will need to email her if we want something. Her poster was really beautiful, it would be nice to include something.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I think we can close this issue b/c I saw you wrote up the $M$ stuff.
