### ISSUE TITLE
latitudinal clines in growth code

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#25]
@LaurelLam-NOAA can you point me to where the code to run the growth analysis is? If we could put the code here or on the google drive somewhere, that would be great. Presumably, one of us will need to run it once we have all the ages. Thanks for running the initial analysis by the way.

**Comment by iantaylor-NOAA** [comment]
We may also want to look at Jason Cope's tool for fitting growth curves with random effects which can account for ageing imprecision (based on [Cope & Punt 2007](https://www.academia.edu/download/43389374/Admitting_ageing_error_when_fitting_grow20160305-28360-1kpm2ev.pdf)): https://github.com/shcaba/Shiny_IGOR.

**Comment by kellijohnson-NOAA** [comment]
Analysis is [here](https://drive.google.com/drive/u/0/folders/1Th747F5au01x5SihNC_EjC43pqWIw4xa)
