### ISSUE TITLE
use the same colors for repeated things

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#27]
We have a variety of figs that have blue and red representing the north and south models, but in some cases blue is north and in other cases red is north. My preference is the first option, with blue representing the colder north and red the warmer south, but I can go with the reverse, or some new pair of colors, as long as we can agree on a standard.

Also, @kellijohnson-NOAA noted that we can align the fleet numbering between the two models so that the same fleet number has the same meaning and the r4ss default colors will always have the same meaning (e.g. WCGBTS will be orange in plots from both models).

- [x] choose colors for north & south -- `r4ss::rich.colors.short(2)`
    * north is blue ("#0000FFFF")
    * south is red ("#FF3300FF")
- [x] get fleet number to be equivalent once models are built

**Comment by kellijohnson-NOAA** [comment]
See 41a9306 for an example of using the colorblindr package to generate colors that might be helpful for the fleet structure, but not needed immediately.

**Comment by kellijohnson-NOAA** [comment]
I am not sure how to number fleets, right now they are just words, e.g., FG, TWL, CA, OR, WA. I think we need to make a function that looks up area and fleet to create fleet.i or something like that. @iantaylor-NOAA, I believe you mentioned that we can have all potential fleets in a model right? I don't want to be over the top about this, I just want to make the best use of r4ss and the plotting capability that it has.

**Comment by brianlangseth-NOAA** [comment]
Ive either just put 1 in my survey comps output, or "FLEETS" or "NA" so as to be easier to catch. Im curious on this too. 
Rerunning everything is doable and clean on the back end but does take some work.

**Comment by iantaylor-NOAA** [comment]
Last time the fleets were
South | North
-- | --
1_CA_TRAWL | 1_N_TRAWL
2_CA_FIX | 2_N_FIX
3_CA_REC | 3_WA_REC
4_CA_TRI_Early | 4_OR_REC
5_CA_TRI_Late | 5_N_TRI_Early
6_CA_NWFSC | 6_N_TRI_Late
7_CA_HookLine | 7_N_NWFSC
&nbsp; | 8_N_Lam_Research

I don't see a benefit in distinguishing between N & S since the names will only be used within the context of a single model and taking that away would allow us to use the same names in both models.

To start the conversation, here's one proposal which would use the same numbering in both models: 

- 1_Comm_Trawl
- 2_Comm_Fix
- 3_Rec_WA
- 4_Rec_OR
- 5_Rec_CA
- 6_Surv_TRI
- 7_Surv_WCGBTS
- 8_Surv_HookLine
- 9_Research_Lam

where the S model would have no WA or OR catch or other data and the N model would have no data for 8_Surv_HookLine. I think there's enough flexibility in time-varying catchability and selectivity that we can have the Triennial survey represented as a single fleet even if we split the time series (something to discuss in another issue probably). 

Many of the r4ss plotting functions only include those fleets with data and others, like r4ss::SSplotData(), include a "fleets" argument which can be used to subset the fleets which get plotted. We may need to tinker with the color settings to ensure the same colors get shown for the same fleets when subsetting fleets, but I think the benefit of orange = WCGBTS (or whatever) will be worth a little extra work.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA Are these fleet numbers confirmed? I have yet to update my data with any fleet numbers.

**Comment by iantaylor-NOAA** [comment]
@Kelli Johnson - NOAA Federal ***@***.***>, do you have any
suggestions for further changes?
I guess the names don't need to be locked in yet, just the numbering at
this stage.

**Comment by kellijohnson-NOAA** [comment]
Looks great.

**Comment by brianlangseth-NOAA** [comment]
Is there a standard for fleet timing? I see the last assessment had comm and rec fleets at mid year (month = 7) but a mix for surveys. Triennial was either month 9.4 or 8.2 depending on year, HKL was variable around 10.5, WCGBTS was 7. Right now I have surveys and rec at month 7.

**Comment by iantaylor-NOAA** [comment]
Good question. My short answer is that I think that the impact of the month settings is tiny so we should just assign all data to the middle of the year, with month = 7.

Here's my thinking:
I think that the biggest benefit of the extra flexibility in timing that SS 3.30 offers and the ability to assign data to a month value other than 7 = mid-year is that it allows exploration of alternative model structures with regard to the number of seasons or subseasons per year without changing the season numbering (which was needed in SS version 3.24). However, Lingcod are long lived enough that a finer seasonal scale is unlikely to have much benefit, would slow down the model a lot (I think speed will scale with the number of seasons per year) and we don't have time for those explorations anyway. So all those survey observations will still get associated with the mid-year growth regardless of month. From reading the "Subseasons and Timing of Events" of the SS User Manual just now, I think the one impact of assigning months other than 7 in an annual model with 2 subseasons per year would be that the fraction of Z = fishing + natural mortality applied to each age before calculation of the compositions. This would mean a late-in-the-year survey like the HKL would see some small difference in the proportion of fully selected fish vs those that are less selected. But I think that impact of that change would be totally confounded with selectivity since the timing is so similar across observations. The triennial timing change is a little bigger but the survey got split anyway so again differences in selectivity would soak up any effect.

A simple (but not trivial) task would be to test the sensitivity of changing all the month values in the 2019 models to 7 to see what difference it makes. I'll start a sensitivity wishlist github issue to keep track of ideas like that.

**Comment by iantaylor-NOAA** [comment]
I just added a new models/fleets.csv file and a get_fleet() function in commit e536564 which will help translate between fleets and also between numbers and names (name in SS, and short and longer labels for use in figure captions etc.). Here are some examples.
The one uncertainty I had on this was how best to deal with the Triennial survey which is now represented as 1 fleet (potentially with time blocks) but was previously 2.

We can also add a column for the color chosen vector to fulfil the original purpose of this issue.

I'm sure there are lots of other ways to revise but I need to move on.

Here are examples from 
```
devtools::load_all()
help("lingcod::get_fleet")
```

```
  # current fleet number for trawl fishery
  get_fleet("trawl")$num

  # plain text label associated with fleet 3
  get_fleet(3)$label_short

  # current fleet number that corresponds to an old fleet name
  get_fleet("TRI_Early", area = "s", yr = 2019)$num

  # current fleet number that corresponds to an old fleet number
  get_fleet(4, area = "s", yr = 2019)$num

  # info on all current rec fleets
  get_fleet("rec")
```

**Comment by iantaylor-NOAA** [comment]
Commit 4aebb10248c370e6fd7ee193461e1a2fe1b9c3c6 adds a `col` input to `get_fleet()`.
Here are some example functions call from `?get_fleet`
```
# current fleet number for trawl using "col" input added 3-June-2021
get_fleet("trawl", col = "num")
# current fleet number for trawl before "col" input was available
get_fleet("trawl")$num
# plain text label associated with fleet 3
get_fleet(3, col = "label_short")
```

@kellijohnson-NOAA, hopefully this solution is adequate. We were going to not deal with this right now but once you put the idea in my head it was painful to continue to use the old way of selecting the output.

At some point we should:
- [ ] decide on a color scheme for all fleets and add a color column to fleets.csv

**Comment by kellijohnson-NOAA** [comment]
Here is a proposal, but happy to hear other suggestions.

Can we use [this paired color palette](https://www.rdocumentation.org/packages/unikn/versions/0.4.0/topics/pal_unikn_pair) for fleets where the darker color would be for the northern model version of that fleet and the lighter color would be for the southern model version of that same fleet
```
unikn::seecol(pal_unikn_pair)
```
![image](https://user-images.githubusercontent.com/4108564/122424779-d815d500-cf43-11eb-8636-6b9bc549bc5e.png)

Here is an example plot of what they would look like for a few fleets.
![image](https://user-images.githubusercontent.com/4108564/122424664-c3394180-cf43-11eb-9d3b-2c4357d6671e.png)

I added two columns to get_fleet() via the csv file
```
             fleet label_short              label_long label_twoletter     fleets_2019.s    fleets_2019.n used_2021.n used_2021.s   col.n   col.s num num_2019.s num_2019.n
1     1_Comm_Trawl comm. trawl        commercial trawl              TW        1_CA_TRAWL        1_N_TRAWL        TRUE        TRUE #3E5496 #8290BB   1          1          1
2       2_Comm_Fix comm. fixed   commercial fixed-gear              FG          2_CA_FIX          2_N_FIX        TRUE        TRUE #008ECE #59C7EB   2          2          2
3         3_Rec_WA     rec. WA recreational Washington              WA              <NA>         3_WA_REC        TRUE       FALSE #077187 #077187   3         NA          3
4         4_Rec_OR     rec. OR     recreational Oregon              OR              <NA>         4_OR_REC        TRUE       FALSE #0A9086 #0A9086   4         NA          4
5         5_Rec_CA     rec. CA recreational California              CA          3_CA_REC             <NA>        TRUE        TRUE #8E2043 #BC7A8F   5          3         NA
6       6_Surv_TRI   Triennial        Triennial Survey                    4_CA_TRI_Early    5_N_TRI_Early        TRUE        TRUE #E0607E #ECA0B2   6          4          5
8    7_Surv_WCGBTS      WCGBTS            WCGBT Survey                        6_CA_NWFSC        7_N_NWFSC        TRUE        TRUE #FEA090 #FECFC7   7          6          7
9  8_Surv_HookLine  H&L Survey      Hook & Line Survey                     7_CA_HookLine             <NA>       FALSE        TRUE #6AAAB7 #6AAAB7   8          7         NA
10  9_Research_Lam    Research    Lam research samples                 8_CA_Lam_Research 8_N_Lam_Research        TRUE        TRUE #B8BCC1 #E1E2E5   9          8          8
11   10_CPFV_DebWV  rec. DebWV recreational CPFV DebWV              WV              <NA>             <NA>       FALSE        TRUE #54BFB7 #54BFB7  10         NA         NA
```

**Comment by iantaylor-NOAA** [comment]
I like it.
I'm not seeing the changes to fleets.csv committed yet, but cutting and pasting from your comment above and modifying make_r4ss_plots_ling() appropriately provides the following paired plots to judge what the colors look like in a few r4ss applications (north left, south right):
![image](https://user-images.githubusercontent.com/4992918/122434474-fd0e4600-cf4b-11eb-9c39-80ed354f68e9.png)
![image](https://user-images.githubusercontent.com/4992918/122434754-39da3d00-cf4c-11eb-99f3-1723a1931354.png)

**Comment by kellijohnson-NOAA** [comment]
Perfect, I didn't push it yet because I wasn't sure if you would like it. Your plots look fantastic, I think. I will push now.

**Comment by iantaylor-NOAA** [comment]
Colors are set. We can re-open or add a new issue if further stuff related to this comes up.
