### ISSUE TITLE
Convert Introduction to markdown

### ISSUE THREAD

**Issue by andi-stephens-NOAA** [iantaylor-NOAA/Lingcod_2021#3]
Formatting and citations.

**Comment by kellijohnson-NOAA** [comment]
- [ ] organize / rewrite Biological Data: Ageing precision and bias section

**Comment by iantaylor-NOAA** [comment]
@andi-stephens-NOAA reorganized the intro and posted to [this Google Doc](https://docs.google.com/document/d/1hEDZrlLSZ0i7YJO3661ZMf0mU6akWofyUKR_AUDv2m8/edit). @LaurelLam-NOAA has added a bunch of text and I've gone through with some edits.

I don't know the best timing to convert this from Google Doc to markdown but it probably makes sense to leave as Google Doc for a little while so folks have a chance to look at the proposed changes and respond to the comments.

**Comment by aliwhitman** [comment]
Hi Ian, would you like me to look over the intro before it goes to markdown?  If so, looks like I’ll need access to that google doc.  I’ll send the official request…  just approve it if you’d like me to review it!

Cheers,
Ali

**Comment by andi-stephens-NOAA** [comment]
Hi Ali and all,

    This "first pass" draft is in a really early state, and I just meant
for Ian and Kelli to okay the direction I was going with it.

Ian just okayed it and I've got suggestions from Owen (one of the original
authors) to add.  Please hold off on reviewing it for now.

Thanks!

--Andi

**Comment by aliwhitman** [comment]
Sure thing!  Thanks Andi!  😊

**Comment by andi-stephens-NOAA** [comment]
Folded Owen's comments into the Intro doc still on the Drive, and accepted all of Ian's and Laurel's changes.

I think we can go ahead and do final review before conversion to markdown!

**Comment by kellijohnson-NOAA** [comment]
@andi-stephens-NOAA I have not taken the time to read the Introduction in detail, but I trust your judgement regarding the best edits to the text and the best way to structure the content. Thank you for doing this. It would be great if you could convert this into a file similar to [this template file](https://github.com/nwfsc-assess/sa4ss/blob/master/inst/rmarkdown/templates/sa/skeleton/11introduction.Rmd) by June 14th, 2021. If this timeline doesn't work for you please let me know and I am sure that we can work something out.

**Comment by andi-stephens-NOAA** [comment]
Sure -- Mid-June is easily doable.  I'll take a look at the template
(thanks for that) and let you know if I have any questions.

Cheers,

--Andi

**Comment by kellijohnson-NOAA** [comment]
Sorry @andi-stephens-NOAA I put the right label but wrote the wrong data, I meant May 14th, 2021. Which is next Friday. Our internal review to Owen is June 21.

**Comment by andi-stephens-NOAA** [comment]
Changes made in commit:  24b1ec0f952345f868b1aaa68e23ef4d1b887d9c

Rmarkdown and bibfile
