### ISSUE TITLE
Convert Washington recreational landings in numbers of fish to mt

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#30]
WDFW provided recreational landings in terms of numbers of fish (as they have done historically) and they need to be converted to fish weight (mt). Please post ideas on how to do this below. In RecFIN, the number of fish is multiplied by the average weight of fish/1000 within a year, port combination to estimate mt of fish. The numbers of fish provided by WDFW are slightly different than those in RecFIN and I haven't fully looked into why, otherwise we could just use the RecFIN values.

**Comment by iantaylor-NOAA** [comment]
A model-based approach to this problem would be to use expected mean body weight from the WA Rec fishery as the basis for the conversion. The figure below shows the expected value for WA Rec mean body weight from 2017 northern model. I think the variability among years (caused by a combination of recruitment variability and variable fishing mortality) is small enough that it can be ignored and an average across years used instead. We could figure out a way to test the impact of this assumption

The biggest issue with this approach is that we would likely want to iterate the calculation at least once after the 2021 northern model is well developed to make sure there weren't big differences in the expected mean body weight.
![expected_mean_body_weight](https://user-images.githubusercontent.com/4992918/114440195-b0d70c00-9b7e-11eb-9468-ecf6f3afdd3b.png)

**Comment by kellijohnson-NOAA** [comment]
Isn't that a bit circular to use expected values from a model to inform input data?

**Comment by iantaylor-NOAA** [comment]
The circularity drives the need to iterate.
The model expectation of mean body weight should be strongly informed by the WA Rec length comps. I think this is essentially what the 2017 model was doing internally to convert input catch in numbers to biomass.

A non-circular approach would be to convert the WA Rec length observations to weights using our chosen weight-length relationship. The values could then be used to either convert catch numbers to catch weight on an annual basis or calculate an average across years. Some kind of average would be needed for the years with catch but no length observations.

**Comment by kellijohnson-NOAA** [comment]
I wonder how RecFIN is doing this because they have numbers and mt. There is a column of average weight for each year. Where does that come from? If I were to have gotten the time series from RecFIN I would have just used the mt column.

**Comment by kellijohnson-NOAA** [comment]
* Yellowtail also dealt with this @iantaylor-NOAA
* varies between 3-4 kg
* any way is going to be fine but it needs to be documented and vetted with Theresa before going forward

**Comment by iantaylor-NOAA** [comment]
The 2017 Yellowtail Rockfish assessment used the same approach as Lingcod 2017 with WA Rec catch input in numbers, not biomass. This added a fair amount of work late in the process during a period where there wasn't much time and resulted in small discrepancies between the catch streams used in the decision table and the associated reported catch as described in the following paragraph (where the calculations are in this script: https://github.com/iantaylor-NOAA/YTRK_doc/blob/master/Rcode/miscellaneous/YTRK_forecast_notes.R)
![image](https://user-images.githubusercontent.com/4992918/114462257-a83eff80-9b97-11eb-86ce-99aaa09df5e7.png)

**Comment by brianlangseth-NOAA** [comment]
Following up from Wednesdays group discussion, [the code](https://github.com/nwfsc-assess/PEPtools/blob/master/R/solve_numbers.R) Chantel mentioned works for the data moderate species.  This code assumes catches are in number for one fleet, and solves the problem of what value to enter in for the first few years of the forecast (which would require catch in numbers). It does require as input, the desired ACL in weight, so we would still need to convert. I used the internal model calculations of catch in weight for my application.

**Comment by kellijohnson-NOAA** [comment]
RecFIN average weight column is generated from the closest 50 records and other algorithms that are very complex. This is just to get in-season projections for the GMT and other people that want to know how much of the TAC is landed and the numbers are not updated after created, thus not good information to use here.
As per Theresa's recommendation, I used mean length from recreational bio data of retained fish. Then @brianlangseth-NOAA 's WL relationship (which I need for all fish without regard to sex) to translate length to weight. This mean weight was then used to translate numbers to mt. Thanks to gchat conversation with @iantaylor-NOAA regarding if sex should be accounted for and we decided to ignore sex because it involves assumptions that the retained catch has the same sex ratio as the sampled biological data which leads to more and more assumptions. So, the least worst assumption is that sex doesn't matter here.

I will close this issue once I update the WL relationship.

**Comment by iantaylor-NOAA** [comment]
Additional figure created during the STAR panel just added to north model doc in 
26a3d1f to help understand the results of this conversion:
![image](https://user-images.githubusercontent.com/4992918/140574018-ac466326-f324-4c37-b6b3-c670568dd745.png)
