### ISSUE TITLE
choose length bins for all models

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#38]
@brianlangseth-NOAA, I looked to your composition processing scripts for guidance on length bins and see that the issue is unresolved:
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/0a2b495ac69fc2e1417a56c391131e72f90182fd/data-raw/survey_comps_datawarehouse.R#L16

The 2017 assessments had different bin structures north and south:
**South**
- Data length bins: 4cm - 130cm by 2
- Population length bins: 2cm - 136cm by 2

**North**
- Data length bins: 10cm - 130cm by 2
- Population length bins: 10cm - 140cm by 2

The age bins are shared among the two models
- Age bins: 0 to 20
- Accumulator age: 25

It would be good to have these match in 2021 and from what I can tell from looking at the data file ([here](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/2019.s.001.001.cou/data.ss_new)), the south model didn't have any observations below 10cm so I would suggest using a 10cm minimum data bin for both models. I'm seeing observations in the 130cm bin for the north model so would suggest retaining that upper limit. The age range seems reasonable based on what I'm seeing in the PacFIN BDS data.

So I would propose these values for both models:
- Data length bins: 10cm - 130cm by 2
- Age bins: 0 to 20

The population length bin and accumulator age only need to encompass all the data so we can see if retaining the 140cm and 25 year values from 2017 makes sense or if we can speed up the model a tiny bit with little impact on results by reducing these to 130cm and 20 years. We could also explore 1cm population bins just in case that makes a difference (as discussed in Monnahan et al. 2016, https://doi.org/10.1016/j.fishres.2015.11.002).

**Comment by brianlangseth-NOAA** [comment]
I will rerun survey comps with this length and age structure. Indeed this was an unresolved item so it will be nice to move forward with it.

**Comment by kellijohnson-NOAA** [comment]
I committed vectors of bins with 6418fabcb26cd6133409c6cbc06bf9cf6cda3bd5. @brianlangseth-NOAA can we close this issue?
