### ISSUE TITLE
text choice U.S. or US

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#39]
Sorry for the trivial question, but U.S. or US?

**Comment by iantaylor-NOAA** [comment]
I vote "U.S.", which also matches what I'm seeing in the Pacific Hake assessments and the recent Dover.

**Comment by kellijohnson-NOAA** [comment]
Sounds good to me. I drive Chris and Andy nutz with this kind of stuff.

**Comment by kellijohnson-NOAA** [comment]
@andi-stephens-NOAA can you double check your Introduction for the use of U.S. instead of US and close this issue once you are done?

Fyi ... U.S. is interpreted by screen readers properly more often then US helping to improve the accessibility of the resulting pdf.

**Comment by andi-stephens-NOAA** [comment]
Waaaay ahead of you guys.  I'm quite pedantic.  People find that annoying, for some reason!
