### ISSUE TITLE
update natural mortality prior

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#40]
I'm splitting this off from #23 because it got long.

**What was done in 2017 assessment report**
Page 41:
> This formula for M provides the median of the prior. The prior is defined as a lognormal with mean ln(5.4/Amax) and a standard error of 0.4384343. Using a Maximum age of 21 for females the point estimate and median of the prior for lingcod is 0.257.

Page 56:
> Priors were applied only to Male natural mortality based on a meta-analysis completed by Hamel (2015). The prior female natural mortality was fixed at the median of the prior based on a maximum observed age of 21, where M = 0.257. See the discussion of natural mortality in the data section for justification of the estimation of sex specific M.

However, in the control file I'm seeing a prior value of -1.53 or -1.532 which matches log(5.4/25), implying a max age of 25. Also, this same prior was applied for females and males when the max observed males is younger than the max for females. The influence of the prior on male M is weak, so I doubt this made much impact as shown in the images below from the standard r4ss plots applied to the 2017 models (north top, south below). The influence of the prior on female M was obviously stronger since the value was fixed at the mean of the prior.

![image](https://user-images.githubusercontent.com/4992918/118165119-cb4c1180-b3d8-11eb-83e1-17dad67d3cf6.png)
![image](https://user-images.githubusercontent.com/4992918/118166262-1b77a380-b3da-11eb-8ad2-99939169efc6.png)

**What should we do in 2021**
The Hamel prior seems like the standard approach and choice to fix or estimate will likely depend on the information in the data about M for each sex, but I think we should update the Amax value used in the prior.

Based on the table of 41,000 PacFIN ages below, I think Amax = 21 would be OK for females, but for males it should be no more than 16. We should also think about the possibility of different values for north and south models.

```
table(bds.pacfin$age1, bds.pacfin$SEX_CODE)
    
        F    M    U
  1   106   56    0
  2  1413  711    8
  3  4016 1819   23
  4  5712 2463   23
  5  5339 2007   41
  6  4227 1297   28
  7  3333  794    6
  8  2500  413    8
  9  1809  223   11
  10 1177  103    4
  11  672   61    3
  12  391   25    3
  13  256    7    1
  14  142    3    0
  15  138    2    1
  16   78    1    0
  17   43    0    0
  18   28    0    0
  19    6    0    0
  20    8    0    0
  21    1    0    0
  23    1    0    0
  24    1    0    0
  27    1    0    0
  35    1    0    0
```
For the 2017 Yellowtail Rockfish assessment, Andi and I chose to use the 99% quantile of ages from the early years (description at https://github.com/andi-stephens-NOAA/YTRK_doc/blob/master/2_Data.Rmd#L41) because there were over 100,000 ages with lots of outliers.

The 99% quantile for Lingcod seems too small, but we could consider a higher quantile like 99.9% or 99.99% as shown in the calculations below for females and males:

```
> quantile(bds.pacfin$age1[bds.pacfin$SEX_CODE == "F"], c(0.99, 0.999, 0.9999), na.rm = TRUE)
    99%   99.9%  99.99% 
14.0000 18.0000 22.7204 
> quantile(bds.pacfin$age1[bds.pacfin$SEX_CODE == "M"], c(0.99, 0.999, 0.9999), na.rm = TRUE)
    99%   99.9%  99.99% 
10.0000 13.0000 15.0016 
```

For the 2021 Dover assessment, I see that @chantelwetzel-noaa has also chosen a value well below the observed max (below text from https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/master/write_up/22biology.Rmd#L17)
> The oldest aged `r spp` was 69 years, captured by the commercial fishery in 1989, not accounting for potential ageing error. Examining all aged fish, a maximum age of 50 was selected. Across all data sources there were limited observation greater than 50 years of age (79 observations in total). In the fish that have been aged from the \gls{s-wcgbt} there have been 41 observations of fish greater than 50 years old (25 females and 16 males). There was little support for a sex-specific differences in maximum age. However, age data are subject to ageing error which could impact this estimate of longevity.  Using a maximum age of 50, the median of the prior was 0.108 yr^-1^ with a standard error of 0.438.

I'll reach out to Chantel and Owen to discuss her approach and see if they thinks it would be fruitful to have a PEP team discussion about the choice of Amax for the M prior and to how to account for outliers, huge sample sizes, and ageing imprecision in that choice. 

@brianlangseth-NOAA, can you add the distribution of ages from survey and rec sources that you've been working with?

Here's a to-do list since they definitely help me not get lost.

- [x] look at distribution of ages from all sources
- [x] discuss approaches for determining Amax for the Hamel prior
- [x] look at Amax by sex based on all ages vs separately for north and south
- [x] decide what to use

**Comment by iantaylor-NOAA** [comment]
Correction: the 2017 north and south models used 0.257 for females which matches the Amax = 21 as stated in the text. The prior value was associated with Amax = 25 but doesn't matter for females since M was fixed.

I chatted with @chantelwetzel-noaa who said the Dover value corresponds to approximately 99.9% quantile of ages. She thought a discussion at a team meeting about development of Amax values might be a good idea. @brianlangseth-NOAA, if there's room on May 19, we could add it to the agenda then.

**Comment by brianlangseth-NOAA** [comment]
See figure below which shows distribution of ages by source and area by sex.  Ive only been working up the survey data and @LaurelLam-NOAA  thesis data, so only include those here.  All survey data have ages <=15, and Laurels thesis has a single 16 and a single 17. 

![Ages_by_Source_Sex](https://user-images.githubusercontent.com/27824606/118199799-b7200880-b408-11eb-8f96-466c7c2523b7.png)

**Comment by iantaylor-NOAA** [comment]
Also consider using Jason Cope's Natural Mortality Tool: http://barefootecologist.com.au/shiny_m to see other estimates of M.

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA For the sake of completeness, the recreational data had one fish aged 23 and one aged 22. Both were females. Neither had more than one read. Next closest was 20.

**Comment by iantaylor-NOAA** [comment]
After discussion with @kellijohnson-NOAA, I'm going to change the M priors to be based on the 99.9% of ages as noted in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/40#issue-891310772 which is 18 years for females and 13 years for males.

**Comment by kellijohnson-NOAA** [comment]
I see you have plots for the priors, do we have plots of all priors that I can include in the doc?

**Comment by iantaylor-NOAA** [comment]
The three informative priors are included in this new fig, but if you want them earlier in the doc, we can do that separately.
https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/figures/compare_north_vs_south_pars.png

**Comment by kellijohnson-NOAA** [comment]
This is brilliant Ian and I am 100% not into redundancy, nor do i care if figures are in order of citation within the document. So, I will mark this one as done!
