### ISSUE TITLE
Sensitivities related to OR indices

### ISSUE THREAD

**Issue by aliwhitman** [iantaylor-NOAA/Lingcod_2021#48]
I wanted to leave some thoughts on sensitivities that should probably be completed related to the OR indices.  The typical ones that I'm familiar with are: 

- [x] including/excluding each of the indices individually

- [ ] including additional variance on the annual estimates, if we think that CIs are too tight (this has been an issue in the past with these indices, but I'm not really sure it's applicable for these)

I'm not sure about others but wanted to open the floodgates.

**Comment by brianlangseth-NOAA** [comment]
Additional uncertainty does not appear needed for CA index, but for the new OR index, uncertainty could probably be reduced compared to the original index as the new CIs are very wide.

**Comment by kellijohnson-NOAA** [comment]
The additional sensitivity wasn't asked for so I am closing this issue
