### ISSUE TITLE
decide how to treat early and late periods of the Triennial survey 

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#49]
As noted in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/32#issuecomment-849047554, the initial 2021 models, (created using script in models/lingcod_model_bridging_newfleets.R) differ a bit from 2019 as shown in the figs below, more so north than south.

I will dig into differences next week but the one change which I think is most likely to be the cause is the data weighting for the Triennial. In previous assessments the two time periods (1980-1992 and 1995-2004) were treated as separate fleets. I thought it would be cleaner to make this is a single fleet with a block on catchability and selectivity. I thought that would simplify our fleet naming system while allowing the same flexibility in treatment of these data.

However, I didn't think about how the separate fleets for TRI_Early and TRI_Late allowed separate data weighting in 2019. The length comp weights were
- 1.51 and 0.17 for 2019 north model
- 0.99 and 2.70 for 2019 south model

These seem like very large differences in weights for data that were collected in hopefully the same way with a small change in survey timing and a bigger change in depth range. Therefore I think treatment as a single fleet with a single weight for all years of length comps makes sense and the differences in model results seem tolerable within the context of all the other changes we're making. For the initial 2021 models I used the mean of the two weights within each model.

I just wanted to note that the change in fleet assumptions (#27) forces this change (though we could work around it be modifying the input sample sizes outside the model), so that if anyone had any concerns we could address them now.

We can discuss assumptions regarding the change in selectivity and catchability across the two time periods later in this same issue if needed.
 
![image](https://user-images.githubusercontent.com/4992918/119716813-605bfb00-be1a-11eb-874f-784114590f9a.png)

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for doing this. Great to see some output. As a team (PEP team meeting in 2020) we decided to model the Triennial as a single survey, so this aligns with that goal and with the code that I used to run the index ;)
I would recommend actually reweighting the models and not using an average b/c all of the values are relative to one another.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA do you think that some of the differences are also due to fitting to more catch data? I think that we should stretch this out into three runs rather than two by cutting off the data at 2019 as an intermediate run.

**Comment by iantaylor-NOAA** [comment]
Actually, I just realized after looking at the new catch runs in #41 that the "new_fleets" models: `2021.n.002.001` and `2021.s.002.001` actually have LESS catch data because the 2019 catch-only projections put the 2017-onward catch as fixed catches at the bottom of the forecast file and for expediency, I turned the forecast off in those runs (e.g. this line https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/2021.n.002.001_new_fleets/forecast.ss#L14) pending complete re-write of our forecast inputs.

Having said all that, I think the final years of catch (either more or less) should have almost zero influence on the model results and the magnitude of the change in this bridging step seems small enough that we don't need to divide it into smaller pieces. However, there's certainly no harm in learning more about what steps led to the changes observed.

**Comment by kellijohnson-NOAA** [comment]
I think it is hard to know what they are going to want parsed out, so you are more than likely correct here regarding parsing it out into more runs is pretty low-hanging fruit and we should just move on.
Is the plan to turn on DM weighting after this, during, or before?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, good question about DM weighting. We should be able to run that via `r4ss::SS_tune_comps(mod, option = "DM")` without too much trouble so it probably makes sense to run it on both the 2019 structure and the 2021 new_fleets structure so we better understand the impact of merging the triennial into a single fleet. 

I just added placeholders for Dirichlet-Multinomial models in both the 2019 and 2021 series in commit 2575c6232f5a3555e4481534faf664786c9a6fbc to [models/README.md](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/README.md).

@andi-stephens-NOAA, could you try the sequence of 
1. copy models from the listed source directories `r4ss::copy_SS_inputs()`
2. load the models into R via `r4ss::SS_output()`, and 
3. run `r4ss::SS_tune_comps(mod, option = "DM")`?

to fill in the models in to those directories (with comments "apply Dirichlet-Multinomial")?

**Comment by andi-stephens-NOAA** [comment]
Yep, I shall.

**Comment by iantaylor-NOAA** [comment]
We will treat the Triennial as a single index in each model with with a single weight applied to the associated comp data and explore changes in selectivity and catchability associated with shift in timing/distribution. Discussion of data weighting options can continue in #60, so closing this issue.
