### ISSUE TITLE
Error trying to access StrataAreas.fn 

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#51]
Im no longer able to run my nwfscSurvey::CreateStrataDF.fn scripts within the lingcod pacakge. Get this error coming from nwfscSurvey::StrataAreas.fn when I run within the survey_lcomps.R function

Error in StrataAreas.fn(strat.df = out, df = SA3_v2021.1) : 
  object 'SA3_v2021.1' not found

My lingcod package is just recently pulled so should be operating fine.

**Comment by iantaylor-NOAA** [comment]
That file was just modified by @kellijohnson-NOAA as discussed in https://github.com/nwfsc-assess/nwfscSurvey/issues/47.
I just updated my clone of the nwfscSurvey package, ran `devtools::load_all("c:/dir_with_package_in_it")` and am able to see that object:
```
head(SA3_v2021.1)
  SUBAREA_ID MIN_DEPTH_M MAX_DEPTH_M MIN_LAT_DD MAX_LAT_DD AREA_HECTARES INPFC_AREA
1         35          55          75       32.0       32.5      2288.251 Conception
2         36          55          75       32.5       33.0     11568.222 Conception
3         37          55          75       33.0       33.5     22776.351 Conception
4         38          55          75       33.5       34.0     27636.455 Conception
5         39          55          75       34.0       34.5     49610.288 Conception
6         40          55          75       34.5       35.0     16188.715 Conception
```
I'm not sure what would be going wrong on your computer. Sorry this isn't very helpful.

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA can you run
```
data(package = "nwfscSurvey")
```
and print the output from the window that pops up here?

**Comment by brianlangseth-NOAA** [comment]
data(package = "nwfscSurvey") gives me. 

Data sets in package ‘nwfscSurvey’:

AFSCforeign_hauls       Example data for AFSCforeign_hauls
SA3                     Example data for strata areas
SA3_v2021.1             
bio_nwfsc_combo         Example data for NWFSC bio data
catch_nwfsc_combo       Example data for NWFSC catch data

**Comment by kellijohnson-NOAA** [comment]
kk 3 more tasks
```
data(SA3_v2021.1,package="nwfscSurvey")
head(SA3_v2021.1)
nwfscSurvey::StrataAreas.fn(data.frame(Latitude_dd.1=32,Latitude_dd.2=34,Depth_m.1=55,Depth_m.2=100))
```

**Comment by kellijohnson-NOAA** [comment]
try
```
devtools::unload(package = "nwfscSurvey")
remotes::install_github("nwfsc-assess/nwfscSurvey",force=TRUE)
```

**Comment by brianlangseth-NOAA** [comment]
> head(SA3_v2021.1)

  OBJECTID MIN_DEPTH_M MAX_DEPTH_M MIN_LAT_DD MAX_LAT_DD AREA_HECTARES INPFC_AREA
1       35          55          75       32.0       32.5      2288.251 Conception
2       36          55          75       32.5       33.0     11568.222 Conception
3       37          55          75       33.0       33.5     22776.351 Conception
4       38          55          75       33.5       34.0     27636.455 Conception
5       39          55          75       34.0       34.5     49610.288 Conception
6       40          55          75       34.5       35.0     16188.715 Conception

> nwfscSurvey::StrataAreas.fn(data.frame(Latitude_dd.1=32,Latitude_dd.2=34,Depth_m.1=55,Depth_m.2=100))

  Latitude_dd.1 Latitude_dd.2 Depth_m.1 Depth_m.2     area
1            32            34        55       100 1773.544
Warning message:
In utils::data("SA3_v2021.1", overwrite = TRUE) :
  data set ‘SA3_v2021.1’ not found

**Comment by brianlangseth-NOAA** [comment]
nwfscSurvey isn't automatically updated when loading lingcod so uninstalling and reloading nwfscSurvey package did the trick. 
Thank you @kellijohnson-NOAA and @iantaylor-NOAA for assistance.
