### ISSUE TITLE
Washington Recreational CPUE index

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#52]
@aliwhitman do you have time to try to help me understand the filtering that is happening in the WA recreational CPUE index. I think that the code base is the same that you are using for OR rec CPUE, where it originally came from Jason Cope for China rockfish. Thanks! I have some of the code working, as in I can run the previous code up to selecting a filtered data set and I have no basis on which to select one given I don't know what all of the filtering even means.

**Comment by aliwhitman** [comment]
I can try!  Can you send me code?  

But in case it helps, the typical OR filters include:  

- bottomfish trips 
- long or short trip times (to filter out, i.e. tuna trips which are long but can be combined with bottomfish sometimes)
- interview times (removes trips where the interview time stamp is incorrect, which would mess up CPUE calculations)
- variants of closed seasons, catches above catch limits (or boat limits with more than one angler) , trips outside of current depth restrictions, ports with small sample sizes
- negative effort calculations
- catch rates above a particular percentile 

There are other filters that I used for lingcod this year, but they are specific to the OR dataset and regulations. Also, the Stephens-MacCall filter was used this year, but that wasn't implemented until cabezon in 2019.

**Comment by kellijohnson-NOAA** [comment]
Largely finished with 7d6c62f

Still need to
- [ ] document methods
- [ ] run more samples
- [ ] update index in model with more samples

**Comment by kellijohnson-NOAA** [comment]
aca762f updated the index with more samples

**Comment by iantaylor-NOAA** [comment]
CPUE index included in data file created for models 2021.n.004.007 and 2021.s.004.007.
Of course the south model doesn't have WA rec CPUE so 2021.s.004.007 is identical to 2021.s.004.004 but everything else is happening in parallel so far so for workflow it was easier for me to just update both north and south to new models than keep track of which one comes from which number.

Thank you for the update @kellijohnson-NOAA.
I'll leave you to close this issue once you checks the box for "document methods".
