### ISSUE TITLE
create new function switch between marginals and conditionals

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#55]
Write a helper function that switches ages between marginals and conditionals.
- [x] assign someone to write this function
- [ ] add this function to the package

**Comment by iantaylor-NOAA** [comment]
Now that we made a plan to do this, I think I can pull it off without too much work, so assigning myself with Friday deadline.

**Comment by iantaylor-NOAA** [comment]
Behind schedule on this, but adding task:
- [ ] fix `add_data()` to make initial setting for survey marginal comps as ghost fleets, not part of likelihood as they are now by accident

**Comment by iantaylor-NOAA** [comment]
Function created a while ago, will be used for the last few sensitivities.
