### ISSUE TITLE
confirm that we have few fishery-dependent ages from CA?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#57]
I'm in the process of adding ages to the model and seeing very few fishery-dependent ages from CA so far.
For instance, as shown in the commands below, we only have 58 fixed-gear ages from all of California (from 1993 and 1994, all of which ended up in the southern model after the PacFIN cleaning and processing). And no trawl samples after 2004.

We also don't yet have any CA Rec ages in the package. Looking at #47, it appears that we shouldn't expect any.

If anyone is aware of any additional fishery-dependent CA ages, please speak up.

```
grep_pacfin_bds <- "PacFIN.LCOD.bds.+RData"
load(dir_recent("data-raw", pattern = grep_pacfin_bds))
bds.pacfin %>%
  dplyr::filter(AGENCY_CODE == "C",
                !is.na(FINAL_FISH_AGE_IN_YEARS)) %>%
  dplyr::select(SAMPLE_YEAR, PACFIN_GEAR_NAME) %>%
  table()
  
           PACFIN_GEAR_NAME
SAMPLE_YEAR GFSH-TRAWL GFTRAWL<8 GILL NET HOOK&LINE
       1993        769         0        9        39
       1994        568         0       20        19
       1995        270         0        0         0
       1996        334         0        0         0
       1997        873         0        0         0
       1998        219         0       38         0
       2001        183         0        0         0
       2002        247         0        0         0
       2003          0        98        0         0
       2004          0       138       15         0
```

Of course we do have lots from fishery-independent sources:
```
sum(ageCAAL_S_WCGBTS$female$nSamps) + sum(ageCAAL_S_WCGBTS$male$nSamps)
[1] 3403
sum(ageCAAL_S_Triennial$female$nSamps) + sum(ageCAAL_S_Triennial$male$nSamps)
[1] 787
sum(ageCAAL_S_HKL$female$nSamps) + sum(ageCAAL_S_HKL$male$nSamps)
[1] 187
sum(ageCAAL_S_LamThesis$female$nSamps) + sum(ageCAAL_S_LamThesis$male$nSamps)
[1] 359

**Comment by kellijohnson-NOAA** [comment]
That matches the 2017 assessment Table 6.

**Comment by brianlangseth-NOAA** [comment]
CA does not age rec - neither RecFIN nor MRFSS data from california have ages. The CalPoly data may have ages (@melissamonk-NOAA only provided me lengths because I only asked for lengths, under the assumption that there were no ages). Other historical CA recreational data do not have ages. 

This matches our experience with data moderate species. Ages just from surveys.
