### ISSUE TITLE
think about options for data-weighting 

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#60]
Thanks @andi-stephens-NOAA for running models with Dirichlet-Multinomial data weighting: 2019.n.004.001, 2019.s.004.001, 2021.n.005.001 and 2021.s.005.001. 
@andi-stephens-NOAA, could you merge your R script which documents the commands you used to run the SS_tune_comps() function with the one I just commit to [models/lingcod_model_bridging_DM.R](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/lingcod_model_bridging_DM.R)?

The change in data-weighting has a large impact on the models as shown at the bottom of this comment. Among the reasons for the difference are
- some variance adjustments > 1.0 in the 2019 models (N_TRI_Early in N and CA_TRI_Late in S for length comps) which can't be achieved by the D-M likelihood (tables below)
- many D-M parameter estimates near the upper bound resulting in equal likelihood weight among many fleets (tables below), and these equal weights are all higher than the Francis weights (other than for the two fleets noted above).

We could consider increasing the input sample size either by incorporating the number of fish sampled (currently everything is numbers of trips or hauls) or by multiplying by an arbitrary factor like 10 to allow more diversity of estimated D-M weights. However, the net result would likely be an increased emphasis on the length comps at the cost of fit to the indices.

It's probably not worth worrying about these data-weighting questions until after we have all the new data in the model, but I just wanted to flag this issue for future consideration.

```
# Francis weights for length comps
mod.2019.n.002.001$Length_Comp_Fit_Summary[,c("Curr_Var_Adj", "Fleet_name")]
     Curr_Var_Adj       Fleet_name
5552    0.1868720        1_N_TRAWL
5553    0.2122190          2_N_FIX
5554    0.1617610         3_WA_REC
5555    0.0171895         4_OR_REC
5556    1.5065000    5_N_TRI_Early
5557    0.1725430     6_N_TRI_Late
5558    0.2223120        7_N_NWFSC
5559    0.2300000 8_N_Lam_Research
mod.2019.s.002.002$Length_Comp_Fit_Summary[,c("Curr_Var_Adj", "Fleet_name")]
     Curr_Var_Adj        Fleet_name
5418     0.216188        1_CA_TRAWL
5419     0.366526          2_CA_FIX
5420     0.024608          3_CA_REC
5421     0.985006    4_CA_TRI_Early
5422     2.702180     5_CA_TRI_Late
5423     0.125107        6_CA_NWFSC
5424     0.210389     7_CA_HookLine
5425     0.890000 8_CA_Lam_Research

# D-M theta values
mod.2019.n.004.001$Length_Comp_Fit_Summary[,c("DM_theta", "Fleet_name")]
       DM_theta       Fleet_name
5322 599.204000        1_N_TRAWL
5323 652.929000          2_N_FIX
5324 137.782000         3_WA_REC
5325   0.353758         4_OR_REC
5326  88.399700    5_N_TRI_Early
5327  61.654800     6_N_TRI_Late
5328 257.439000        7_N_NWFSC
5329   2.162260 8_N_Lam_Research
mod.2019.s.004.001$Length_Comp_Fit_Summary[,c("DM_theta", "Fleet_name")]
       DM_theta        Fleet_name
5076 852.487000        1_CA_TRAWL
5077 673.298000          2_CA_FIX
5078   0.687865          3_CA_REC
5079  73.996000    4_CA_TRI_Early
5080 125.632000     5_CA_TRI_Late
5081 290.854000        6_CA_NWFSC
5082 236.952000     7_CA_HookLine
5083  28.648900 8_CA_Lam_Research
```

![compare_2019 n 002 001_2019 n 004 001](https://user-images.githubusercontent.com/4992918/121542877-57902b00-c9bd-11eb-80db-cae9c88d5105.png)
![compare_2019 s 002 002_2019 s 004 001](https://user-images.githubusercontent.com/4992918/121542886-5959ee80-c9bd-11eb-9845-04a9e4cb183c.png)

**Comment by kellijohnson-NOAA** [comment]
Notes from chatting with @iantaylor-NOAA 

## Next steps

- [ ] get all data in the model and see if the DM parameters are still hitting the bounds
- [ ] if yes to (1), then explore Francis weighting because of the use of CAAL, cite AEP's work
- [ ] potentially explore input sample sizes

**Comment by iantaylor-NOAA** [comment]
Data weighting for current model using Francis method produces plausible results. I'll open a new issue related to a wishlist for future data weighting options.
