### ISSUE TITLE
choose what CA recreational CPUE to use

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#62]
Building on #56 but now worrying about which rec CPUE to actually use.

The 2017 lingcod south model had no recreational CPUE index in final base model. The [STAR report from 2017](https://drive.google.com/drive/folders/1vJgeZkBFE2UYZK2Um2xpc4mMxLKCRDSZ) describes this element of the south base model as follows:
> Fishery-dependent indices for the southern stock comprised a commercial trawl CPUE index from PacFIN logbook data (1981-1997), a CA onboard observer recreational index for (1987-1998 and 2002-2016), and a central CA dockside recreational index (1980-1997). The last two indices were included in an alternative draft base model brought to the STAR but they were not used in the final southern base model (see Request 2.2).

Here's text from the "Request 2.2" section:
> Discussion of the results revealed that, although the “Wadsworth index” (Central CA dockside recreational index) had been employed in the 2009 previous assessment, the methods employed when calculating the indices were not fully documented and techniques for analyzing recreational dockside data have advanced since 2009 in connection with the assessments of nearshore species conducted in 2015 (PFMC, 2015). For the current assessment, with the information and data available, it would be difficult to defend the use of this index when calculating the likelihood and fitting the model. If the Wadsworth index is to be used in future assessments, the data employed and methods used for developing the index should be re-examined and the analyses reworked so that the approaches employed may be critically assessed and, if necessary, refined. 

The refinement has now taken place, but we're still faced with somewhat redundant data that probably should not all be entered into the model.

For what it's worth, here's a plot of the values in the 4 new indices from recreational fisheries in CA (happens to be the first ggplot that I've ever made for use in the real world) [github issue edited to fix mismatch of older code with newer fig that got pasted]:
```
data_index_cpue %>%
 dplyr::filter(index %in% c(5,10), area == "south") %>%
 dplyr::select(year, obs, source) %>%
 ggplot(aes(x=year, y=obs, color=source)) + geom_point()
```
![image](https://user-images.githubusercontent.com/4992918/121945373-90efd000-cd08-11eb-8b9c-38a09b1717d4.png)

Tasks:
- [x] determine whether it would make sense to stitch the early and late time periods of the onboard CPFV indices together as was done in 2017 (before the index was removed)
  - [x] I'm guessing not because of differences in assumptions about treatment of discards, but would need @melissamonk-NOAA to confirm
- [x] choose which Rec_CA indices to use in the initial models (the two more recent indices are so similar, I don't see much value in adding both)

**Comment by kellijohnson-NOAA** [comment]
In 2009 the MRFSS dockside index was used and this index ended in 1999. STAR Panel didn't like that the index standardization methods were not documented or updated in 2017. The red and green were stitched together after separate workups, which was also removed. Removed b/c it had a big influence on the model leading to less of a good fit to the bottom-trawl survey. 
CRFSPR is the private rental boat and will have tight cv because it is hundreds of thousand of trips, sampler examined catch at docks. Will be included as a sensitivity.
onboardCPFV has more accurate data and info on where they caught the fish
DebWV will be included as a separate index.
MRFSS - time-varying catchability and truncate the index to be the main time series and not include the last three data points

**Comment by kellijohnson-NOAA** [comment]
Only removing 1999 from MRFSS and not 1995 and 1996 because we are making one timeseries. We will explore the fit to these two years and then talk about removing them if they are not estimated well. But there was going to be a large hole in the time series given we are combining MRFSS and CPFV.

**Comment by iantaylor-NOAA** [comment]
indices added as discussed here and shown in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/56#issuecomment-861901456
