### ISSUE TITLE
consider using SS version 3.30.17.01 (when available)

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#63]
SS version 3.30.17.00 was released on Friday but contains an issue https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/183 which would be a problem for exploring the Dirichlet-Multinomial likelihood, even as a sensitivity in the Lingcod model. A bug fix should be forthcoming soon and will likely allow a seamless change from SS version 3.30.16.02 that we're using now.

Benefits of switching include all the changes listed at https://vlab.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/view_message/15698143

We would want to 
- [x] run some model with 3.30.17.01 without estimation to confirm that it runs without crashing
- [x] run some model with 3.30.17.01 to see if it gets very close to the same result as the 3.30.16.02 model and if not decide whether to look deeper at the differences.

@kellijohnson-NOAA do you have any concern with making the switch if the new version passes the checks above?

**Comment by kellijohnson-NOAA** [comment]
I think switching is fine as soon as the bug is fixed, which it sounds like will be later today.

**Comment by k-doering-NOAA** [comment]
Exes for 3.30.17.01 now available: https://vlab.noaa.gov/web/stock-synthesis/document-library/-/document_library/0LmuycloZeIt/view/6427430

**Comment by iantaylor-NOAA** [comment]
Running a north model (2021.n.008.003) using new 3.30.17.01 executable ([VLab here](http://api.admb-project.org/classfunction__minimizer.html#a8e1f3eae74288082c00d076e4a674ac3)) produced identical results with a few small differences in output worth noting
- 3.30.17.01 ran 5% faster than 3.30.16.02
- There are 12 fewer unused `Impl_err` parameters
- M parameters have been given names which reflect the functional form that they're associated wtih, in this case from NatM_p_1_Fem_GP_1 to NatM_uniform_Fem_GP_1. This would require a tiny change to this script that I've been using https://github.com/iantaylor-NOAA/Lingcod_2021/blob/53e0ae6f96df59b1988e44a2a516e58162233c0c/models/lingcod_model_bridging_change_ctl.R#L41-L49. I don't know if this impacts the profile code, but again the change wouldn't be hard.

There's also the potential that some of the bug fixes that don't impact this particular model could play a role in some alternative model that we haven't yet explored. It also uses ADMB 12.3 which includes the new [-hess_step](http://api.admb-project.org/classfunction__minimizer.html#a8e1f3eae74288082c00d076e4a674ac3) option (thanks to Cole Monnahan).

It's probably wise to make the switch, but I'm not sure the best timing. I can start with 
- [ ] modifying lingcod_model_bridging_change_ctl.R to work with either old or new M par names

**Comment by kellijohnson-NOAA** [comment]
I believe, for the profile all it would take is changing the parameter name in diagpars.csv. So, not a big deal.

**Comment by iantaylor-NOAA** [comment]
ss.exe updated in package in commit 7e10ffc4cc100a4590cdcc750eafbfb1baef6100. 

Whoever first runs a profile after pulling the changes should update diagpars.csv. For purposes of the ...change_ctl.R script, I think "NatM_.*_Fem" seems to work for both setups.

**Comment by iantaylor-NOAA** [comment]
Profiles are running with updated diagpars.csv (commit e7c822fd3b99067f247a2daaff23eb34ff8e2dde)
