### ISSUE TITLE
figures - map

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#64]
@iantaylor-NOAA do you have code or a png for your map with the management line? Or, does anyone else have an idea for an epic map to include as the relevant area for lingcod?

**Comment by iantaylor-NOAA** [comment]
Code and map added in d89502b7348fe6de53031d21ea60bf04c0f20136.
Link to raw image: https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/figures/map_of_stock_boundaries_40-10.png

Please feel free to make any changes. As noted in the roxygen comments, the colors have default
> unikn::usecol(pal_unikn_pair, 16L)[c(2,10)] as used in data-raw/lingcod_catch.R but could/should be updated to use values stored in the package
However, that sort of thing could wait until next time.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA and sorry I didn't look for it before asking. I don't see a call to the function in a script though, do you want me to add that? I am going to add a caption and alternative text as well. Proposed text ==
```
"Map of the investigated area. The dashed line and colors delineate the northern (blue) from the southern (red) assessed area."
"Outline of U.S. west coast with stocks delineated at forty degrees ten minutes north Latitude."
```

**Comment by iantaylor-NOAA** [comment]
Sorry, yes please add a script and caption.
Your proposed caption highlights for me that I've been using a mix about "southern", "south", "South". Could we pick one?

**Comment by iantaylor-NOAA** [comment]
Script with caption added and map included in package, all thanks to @kellijohnson-NOAA.
