### ISSUE TITLE
check data inputs for obvious errors

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#65]
Initial models with all planned data included are 2021.n.004.002 and 2021.s.004.002. Please take a look at the figures below showing presence/absence of different data sources by year and report anything that jumps out as erroneous (north above, south below). I know it's late in the process, but good work everybody getting to this stage.

You're all welcome to scan through the data files themselves (not so satisfying once you get to the composition data):
https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/models/2021.n.004.002_new_data/ling_data.ss
https://raw.githubusercontent.com/iantaylor-NOAA/Lingcod_2021/main/models/2021.s.004.002_new_data/ling_data.ss

Please check a box once you've taken a look to confirm that the data sources you provided, are familiar with, and/or helped work up, seem to be in the right place.
- [x] @aliwhitman (anything associated with Oregon including commercial fixed gear index)
- [x] @andi-stephens-NOAA (mean body weight, commercial discard comps--buried amidst commercial retained comps)
- [x] @brianlangseth-NOAA (rec and survey comps)
- [x] @iantaylor-NOAA (commercial comps, mean body weight, discards)
- [x] @kellijohnson-NOAA (catches, indices)

![data_plot](https://user-images.githubusercontent.com/4992918/122153832-9fc5a800-ce18-11eb-93c3-49eb6aafa35d.png)
![data_plot](https://user-images.githubusercontent.com/4992918/122153858-ac4a0080-ce18-11eb-99e0-1438818e0dc8.png)

**Comment by aliwhitman** [comment]
Looks good from my perspective. Can't check the box for some reason :(

**Comment by iantaylor-NOAA** [comment]
Thanks @aliwhitman, I have no idea why the check box didn't work--clearly you were signed into github since you were able to reply to the comment. Regardless, I just checked the box next to your name.

**Comment by brianlangseth-NOAA** [comment]
These years look good - though hard to really see the composition data. As previously mentioned the CAAL comps for OR and WA are available for the north model (#75). The are within the pacakge ageCAAL_N_OR_Rec, and ageCAAL_N_WA_Rec. 

The length samples for debWV CPFV extend one year back compared to the index. Lengths extend to 1987 while the index to 1988. Would be easy enough to exclude 1987 lengths, if that is what should be done, as I trust @melissamonk-NOAA to be on top of how best to treat the debWV data. Sample size for 1987 lengths was not particular low so dont know why the difference between lengths and the length exist.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for making adding data so automated.
