### ISSUE TITLE
decide on capitalization of lingcod/Lingcod

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#67]
This was discussed at assessment team meeting today.

@andi-stephens-NOAA and I are fans of the AFS rules (pasted below from page 2 of https://fisheries.org/docs/pub_style10.pdf) but many folks don't like it (e.g. "Seeing it as Lingcod rather than lingcod makes my eye twitch."). This is pretty inconsequential compared to so many other decisions we have to make, but this github issue can help us track discussion if you have thoughts to share.

I suppose we could use a parameter to build parallel documents with different capitalization schemes, but we won't.

![image](https://user-images.githubusercontent.com/4992918/122267238-827ff080-ce8f-11eb-811e-328cb9693cc5.png)

**Comment by iantaylor-NOAA** [comment]
I just found [NOAA/NMFS tech memo guidelines](https://spo.nmfs.noaa.gov/sites/default/files/Tech%20Memo%20Guidelines.pdf) which say "Do not capitalize the second part of the common name, although AFS recommends this". They say that they follow guidance from AFS on fish nomenclature so this is clearly a a specific choice that somebody at NOAA/NMFS made. Therefore, I'm now of the opinion that while I may like capitalized common names in general, we should use lowercase "lingcod" except at the beginning of sentences.

Also in a recent meeting the chair of our review panel said that they prefer lower case (while acknowledging that it doesn't really matter).

@kellijohnson-NOAA if you object, I'm happy to go with capitalized, but if not, here's a checklist:
- [ ] convert \`r Spp\` to \`r spp\` except at the beginning of sentences or other contexts where capitalization is needed.

**Comment by kellijohnson-NOAA** [comment]
we will also need to change `utils_name("Common")` to `utils_name("common")` where it is used. I like `utils_name()` b/c it works outside of knitting a document for the sa4ss template, but either work just fine.

**Comment by kellijohnson-NOAA** [comment]
I think I fixed this everywhere using search and replace.
