### ISSUE TITLE
Oregon Fishery Independent data

### ISSUE THREAD

**Issue by aliwhitman** [iantaylor-NOAA/Lingcod_2021#68]
@kellijohnson-NOAA @iantaylor-NOAA Just wanted to check with you guys about how you would prefer to include the Oregon fishery independent data/write-ups in the assessment document.  To refresh your memory, these include 1) a range of abundance estimates from video lander data and 2) a raw CPUE index from our marine reserves hook and line survey.  

If I might suggest an approach, it might make the most sense to refer to these two in the main document (in the Fishery Independent data section) but include the main explanations/data/graphs in a separate appendix for each dataset.  The trick might be to add discussion later (once we have a happy amazing base model) about how the data or trends from these two datasets may or may not support the information coming out of the model.  That last bit may come down to the wire.  

Thoughts on my above proposed approach?

**Comment by kellijohnson-NOAA** [comment]
@aliwhitman thanks for checking in. Moving things to the appendix is only going to be for the analysis that now have more than 10+ pages of text regarding how indices were worked up. 

We are hoping to get the write up of how the data were treated done by Friday and then next week we will work on adding text regarding model fits.

**Comment by aliwhitman** [comment]
Sure, they're already written up and not that long.  So I will add those to the document folder by the end of today.  One has a couple of tables and figures, which I will add separately as per instructions from Monday.  Then I will move on to work on OR data sections.
