### ISSUE TITLE
add and refine forecasts

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#73]
Thanks @kellijohnson-NOAA for the reminder to do this.

Forecast files added in commit 2e58f04afc835ea96f7682dc5079a0fcd1ed8988 based on 2019 models with minor changes to strip away info specific to that year. Models 008.002 include these files and are run without estimation.

TODO list for forecast file:
- [x] create initial forecast file
- [x] update the time-varying buffer: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/e8a0d4f4559263c50de0ee7e52acd1f146401de3/models/lingcod_forecast.R#L35-L37
- [x] add fixed catches for 2021 and 2022: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/e8a0d4f4559263c50de0ee7e52acd1f146401de3/models/lingcod_forecast.R#L44-L45
- [x] make a projection table.
- [x] add call to `table_projections()` in the doc

**Comment by iantaylor-NOAA** [comment]
Somewhere in the progressing of modeling, the forecast files added in 008.002 got lost. That's fine for the diagnostics (probably makes the models slightly faster to have no forecast). Tomorrow I will add them back and re-run the north and south models with Hessian and forecast for purposes of the figures and tables in the first draft report.

We can also add in the table of time-varying sigma values while we're at it.
@chantelwetzel-noaa, can you remind us where these values are available, or should we just copy them from your excellent Dover assessment (although I guess we first need to confirm the Pstar chosen for lingcod).

**Comment by chantelwetzel-noaa** [comment]
A simple function to calculate a vector of time-varying buffers is located [in the PEP tools package](https://github.com/nwfsc-assess/PEPtools/blob/master/R/buffer_fxn.R).  If the Pstar was set to 0.45 you would call the function as:

`
get_buffer(years = 2021:2032, sigma = 0.50, pstar = 0.45)
`

This vector can then be put in the forecast file:

-1 # Buffer:  enter Control rule target as fraction of Flimit (e.g. 0.75), negative value invokes list of [year, scalar] with filling from year to YrMax 
2021 1 
2022 1
2023 0.935
2024 0.930
2025 0.926
2026 0.922
2027 0.917
2028 0.913
2029 0.909
2030 0.904
2031 0.900
2032 0.896
-9999 0

**Comment by iantaylor-NOAA** [comment]
Thank you @chantelwetzel-noaa! I knew there was a trick. 
Now we just need to augment that function to look up what the Pstar is. 

I'm guessing we can assume Pstar = 0.45 for now and maybe somebody better connected to the PFMC like @aliwhitman or @melissahaltuch-noaa can confirm.

And for our future selves to remember, sigma = 0.50 is the current Category 1 minimum sigma for the Pstar calculation, which will likely apply to both models as the estimated uncertainty is lower.
```
mod.2021.n.015.003$Pstar_sigma
[1] 0.1537135
```
I can't remember which recent south models had a Hessian, but while uncertainty is higher than in the north, I still think the estimated Pstar_sigma is below 0.5.

**Comment by chantelwetzel-noaa** [comment]
It looks like a Pstar = 0.45 was used in the 2019 catch-only updates for north and south lingcod.  In the forecasts for the in review assessment Pstar should likely be fine.  However, the Council may request a lower Pstar run depending upon the status but this request would most likely come later this fall during the harvest specification process.  You could also check in with the GMT representative for your STAR panel, Lynn Mattes, to ensure that you are on the right track.

**Comment by iantaylor-NOAA** [comment]
I didn't get to this today but will add forecasts to north and south models tomorrow. Now I'm going to go to sleep.

**Comment by kellijohnson-NOAA** [comment]
The current base model for the south at least doesn't have 2020 and 2021. @iantaylor-NOAA do you want me to work on this? It is needed for #108
```
    area Year     OFL     ABC  ACL      Obs      Exp
1  South 2011 2523.00 2102.00 2102 213.1944 213.1944
2  South 2012 2597.00 2164.00 2164 273.5600 273.5600
3  South 2013 1334.00 1111.00 1111 428.6714 428.6714
4  South 2014 1276.00 1063.00 1063 503.0640 503.0640
5  South 2015 1205.00 1004.00 1004 711.6984 711.6984
6  South 2016 1136.00  946.00  946 675.6463 675.6463
7  South 2017 1502.00 1251.17 1251 546.1819 546.1819
8  South 2018 1373.00 1143.71 1144 449.4559 449.4559
9  South 2019 1142.95 1092.66 1039 389.2262 389.2261
10 South 2020  977.12  934.12  869 286.4990 286.4990
11 South 2021 1255.00 1162.13 1102       NA       NA
12 South 2022 1334.00 1229.95 1172       NA       NA
```

**Comment by iantaylor-NOAA** [comment]
I don't remember what Lynn Mattes provided. 
For 2021 and 2022 catch we could either provide a fixed input for each fleet as in 
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/2019.s.001.001.cou/forecast.ss_new#L67-L81
or we could just run the models with the default HCR and replace with inputs later.

Forecast files were created for the 008.002_add_forecast models using the script 
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/lingcod_forecast.R.

**Comment by kellijohnson-NOAA** [comment]
From email titled "lingcod projections from GMT"
<html>
<body>


Year | IFQ- trawl (lbs) | IFQ-FG (lbs) | Grand Total (lbs)
-- | -- | -- | --
2011 | 13,209 | 21 | 13,230
2012 | 24,706 | 704 | 25,410
2013 | 23,746 | 51 | 23,797
2014 | 30,055 | 324 | 30,379
2015 | 56,499 | 33 | 56,532
2016 | 41,464 | 119 | 41,583
2017 | 49,223 | 479 | 49,702
2018 | 102,302 | 47 | 102,349
2019 | 162,900 | 127 | 163,027
2020 | 121,456 | 594 | 122,050
2021 | 14,679 | 30 | 14,709


</body>
</html>

**Comment by kellijohnson-NOAA** [comment]
2021-22 the trawl/non-trawl ratio is changing to 40:60

**Comment by iantaylor-NOAA** [comment]
OK, let me put together an initial forecast file in which we use the recent 5-year average ratio of commercial to rec catch and then apply a 40:60 split for the commercial and use the recent averages for each rec fleet. Lynn can update us (probably she has already and I'm just scattered) and we can refine as needed.

**Comment by kellijohnson-NOAA** [comment]
No, the email said she would ask the GMT and then she got back to us with ratios but not catches.

**Comment by iantaylor-NOAA** [comment]
Models with 2 years of fixed catch based on recent 5-year average with 40:60 TW:FG split added in 8b92b3a.
Fixed catches are at the bottom of the forecast file and in the timeseries output.
I'll be off the rest of the afternoon and back this evening.

**Comment by iantaylor-NOAA** [comment]
Note: forecast.ss is written by [models/lingcod_forecast.R](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/lingcod_forecast.R) and easy to make changes as needed.

**Comment by iantaylor-NOAA** [comment]
table_projections() function now working for both models as of 9ff5bd3.
@kellijohnson-NOAA, can you add the call to that function where you think is appropriate?
The r4ss::SSexecutivesummary() function will get run automatically the first time you call this for any model but after that it will find the csv file required.

**Comment by iantaylor-NOAA** [comment]
After many rounds of changes, and too much overthinking, I believe the projection table is sorted out with regard to OFL vs ABC vs ACL in commit 5436f3c2a09efb43466f7edf1621a54419912247. 

@kellijohnson-NOAA, if those on email discussion about this approve the "Saturday 6am" version of the table, then the "alt_projection" branch can be deleted and the newly modified `table_projections()` in the main branch can be merged with any uncommitted changes you have and the south Exec Summaries updated with the corrected table. The north table created by the revised code seems to exactly match the one already submitted (because the stock is always above B40%).

I can help get these changes integrated into `r4ss::SSexecutivesummary()` in the future.

**Comment by iantaylor-NOAA** [comment]
Added to "To do r4ss" and leaving open to help me remember to propose changes to `r4ss::SSexecutivesummary()` as discussed above (https://github.com/iantaylor-NOAA/Lingcod_2021/issues/73#issuecomment-898895633).

**Comment by iantaylor-NOAA** [comment]
Issue summarized in https://github.com/r4ss/r4ss/issues/628, now closing this one.
