### ISSUE TITLE
add some custom figures

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#74]
Here are some plots of model output which aren't created by r4ss that I find useful both for model selection and reports:
- [x] plot of all indices together
- [x] plot of time-varying retention (see https://github.com/r4ss/r4ss/issues/322)
- [x] plot of time-varying selectivity (as above)

First attempt at a quick and dirty `plot_indices()` function is added in 26163794266a224f008027da9497008b6a42c818 which looks like the following (for the 008.004 models, north above, south below). Helps me see how noisy the south survey indices are.
![image](https://user-images.githubusercontent.com/4992918/122625554-a80d2580-d05a-11eb-8e43-0c48af9e0ba3.png)
![image](https://user-images.githubusercontent.com/4992918/122625559-afccca00-d05a-11eb-819d-82fcdaad7f2d.png)

**Comment by iantaylor-NOAA** [comment]
Custom index figures added in 4e873ac. They should be created by `unfit/lingcod_builddoc.R` and appear in a "custom_plots" folder within the model file.
@kellijohnson-NOAA, can you tell me how to reference it within 53figures.Rmd so I can add this one and others as I go?
That is, I'm assuming I want something like the following, only with [model path] filled in.
```
```{r, results = "asis"}
do.call(
  sa4ss::add_figure,
  utils::read.csv(file.path("..", "models", [model path],  "custom_plots", "index_data_all_fleets.csv"))
)
```

**Comment by kellijohnson-NOAA** [comment]
Do you have a csv for each of them or did you generate a single csv with multiple rows? If the former, then yes what you have is correct. If you did the latter, then you can call them all in at once, which means they will be plotted together in the order you specify with `add_figure_ling`. [model path] is in `params$model`

**Comment by iantaylor-NOAA** [comment]
It's the former so that they can be put in different places (data vs fits).
@kellijohnson-NOAA, can you check my changes to 53figures.Rmd in b6c279d8f0619a4256ef75ccc02880bcd36f26be to make sure it looks OK?

I also added section headers following the approach used in https://github.com/iantaylor-NOAA/BigSkate_Doc/blob/master/9_4_Figures_Assessment.Rmd, but feel free to change those.

**Comment by kellijohnson-NOAA** [comment]
Two fixes in 4567d39

**Comment by kellijohnson-NOAA** [comment]
Sorry, should have caught that `model` is relative to doc. So you need to remove `"..", "models"` from `file.path`

**Comment by iantaylor-NOAA** [comment]
Got it, thank you. Fixed in b5a1e13 (assuming I'm understanding this correctly).

**Comment by iantaylor-NOAA** [comment]
Custom selectivity plots added in 8faaa51 (examples below--north top, south bottom) and included in 53figures.Rmd in 904001a2853f4b394574dd201515dc6a010012d2.
These should be created along with csv files by make_r4ss_plots_ling() when building the document.
We can modify in the future as needed, but hopefully this is good enough for now.

![image](https://user-images.githubusercontent.com/4992918/123366377-f4f66d80-d52c-11eb-8bca-fe014032b737.png)
![image](https://user-images.githubusercontent.com/4992918/123367632-23754800-d52f-11eb-9eed-727124f1ec19.png)

**Comment by iantaylor-NOAA** [comment]
The make_r4ss_plots_ling() function has proven useful but has a problem with dev.off() not being used somewhere. 
This is what I use to run the function:
```
make_r4ss_plots_ling(mod, plot=1:26)
dev.off()
make_r4ss_plots_ling(mod, plot=31:50)
```
