### ISSUE TITLE
next set of model changes to explore

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#76]
The 008.006 models (or 008.005 + change to discards--I still need to sort out git after breakfast) discussed in #59 look like a good starting point for some refinements that I'll suggest in this new issue. Some of these could be sensitivity analyses, but posting to a separate issue from #43 will make it more clear that these are things that we could work on right away.

All these are pretty small things so not a big deal at this stage.

- ~Variability in growth for the **north** model looks a little funny (left in fig below)~ **[update: alternative models had worse likelihood and looked even more funny]**
  - try changing CV_Growth_Pattern from "0 CV=f(LAA)" to "1 CV=F(A)"
  - and/or try changing Growth_Age_for_L2 from 10 to 25 (or 999 to use as Linf) [edit: south model has Age_for_L2 = 14]
  - probably worth making this change in both **north** and **south** models
  - I think total likelihood is a fine way to select between these options as the number of parameters isn't changing although looks less funny also seems like a reasonable diagnostic to select among the options
  - ![image](https://user-images.githubusercontent.com/4992918/122645899-a6327900-d0d1-11eb-83ea-4841f156b24b.png)
- some **north** model fleets have estimated asymptotic selectivity
  - @james-thorson-NOAA has argued that there is value in estimating the descending slope parameters rather than fixing them at the upper bound because you capture the uncertainty in selectivity better and allow flexibility to change in sensitivities and profiles. However, if those parameters degrade model performance it would be better to deal with them somehow. Perhaps the adnuts diagnostics can help here.
- **north** model parameters Q_extraSD_2_Comm_Fix(2) and Q_extraSD_4_Rec_OR(4) are hitting the lower bound of 0. This suggests that the the workup of these indices (both thanks to @aliwhitman) included good initial estimates of uncertainty and the indices are consistent with other source in the model so no extra SD is needed for tuning. Therefore we should probably just turn off those parameters and use the input uncertainty.
- **south** model index things worth thinking about
  - Triennial is very noisy (fig below) 
    - normally I would think we should add an extraSD parameter (none are present for surveys) to acknowledge the additional variability not included in the VAST output, but the R0 profile (shown in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/59#issuecomment-864402967) indicates very little influence of this index, so we could probably just leave it
    - ![image](https://user-images.githubusercontent.com/4992918/122646396-c105ed00-d0d3-11eb-8644-596323f82089.png)
  - Fit to rec CA index isn't great and estimated extraSD is pretty large to allow the lack of fit. However, a rec index like this probably shouldn't be given too much weight anyway and the overall trends are OK. We could add a nonlinearity parameter (as was used for Rec indices in 2009 Yellowtail Rockfish assessment) to model hyperstability/hyperdepletion, but I don't see a particular need for a change there.
- Consider some data-weighting for discard rates and mean body weight of discards
  - @kellijohnson-NOAA didn't you do something like this for Sablefish?
  - I think the value of including mean body weight in assessments is somewhat debatable but here those data are fit reasonably well and don't seem to have much influence on results
- Explore potential convergence issues with some of the profiles (e.g. **north** model M profile shows a big jump above M = 0.4, and **south** model jump in #59).

**Comment by kellijohnson-NOAA** [comment]
Running Cole's regularization routine on the south model now. We can change the profile of M to different values if you want, just change it [here](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/inst/extdata/diagpars.csv).

**Comment by kellijohnson-NOAA** [comment]
See tuning code here 992e05eb73ce05a17f1113e06f1108a18038345f

**Comment by iantaylor-NOAA** [comment]
Investigation into growth variability options failed to produce anything better than what we were working with.
Also, the north and south models both had Growth_Age_for_L2 = 14 from the beginning--I'm not sure where I was seeing 10 that caused me to think that they mismatched.

This evening I'll explore on tuning the discards and mean weight thanks to the Sablefish code, as well as maybe tinker with a few selectivity parameters, and call it good enough for now and switch to focusing on writing tomorrow.

**Comment by kellijohnson-NOAA** [comment]
There are a few selectivity parameters that are highly correlated, mainly Triennial and Deb WV, but also one commercial trawl parameter in the southern model. Then, the correlation of the added sd for the Deb WV index is banana shaped with a few other parameters. The median of the posterior and the MLE are small ~ 0.05. I suggest we turn it off rather than poorly estimating it as long as the fits remain sufficient without it, which they should.

**Comment by iantaylor-NOAA** [comment]
Models 2021.n.009.001 and 2021.s.009.001 include a few changes based on the adnuts diagnostics provided by @kellijohnson-NOAA. 

Changes from 008.006 models include: 
- treating the Triennial as a continuous time series rather than having a block on Q and selectivity 
  - both models had issues with either an early or late Triennial selectivity parameter, reflecting the fact that each time period had at most 5 years of somewhat sparse observations of lingcod
  - it turns out that the block on Q wasn't working right, but getting it to work correctly in a separate model didn't improve things
- fixing the Q_extraSD_10_CPFV_DebWV = 0 in the south model based on comments in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/76#issuecomment-864474450
- using SS version 3.30.17.01

The results are very similar to the previous round of models as summarized in the figures below:
![image](https://user-images.githubusercontent.com/4992918/122675884-52d33000-d190-11eb-8cb5-09f8f3361b56.png)

I think these models are definitely good enough for the internal review (#77) so we can leave our computers to run some diagnostics on their own for a while. I think that cleaning up a few problematic parameters may allow the profiles to be smoother and more informative.

**Comment by kellijohnson-NOAA** [comment]
Great. I am re-running the regularization right now. I can start the retros after that. So, do you want to change [diagpars.csv](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/inst/extdata/diagpars.csv) to span the values you want to explore and set those to run. FYI if no area is declared then the same values are used for each area. The code to run it after you change diagpars and save it, would be
```
setwd(dirname(system.file(package = "lingcod")))
run_investigatemodel(basemodelname = get_dir_ling(area = "n", num = 9, sens = 1), run = "profile")
run_investigatemodel(basemodelname = get_dir_ling(area = "s", num = 9, sens = 1), run = "profile")
```

**Comment by iantaylor-NOAA** [comment]
Great, I will set those up to run and report back on the results sometime tonight or early tomorrow.

**Comment by kellijohnson-NOAA** [comment]
Moving discussion from chat to here ... the 2011 trawl time block is poorly estimated in the southern model.

do you recall why we have the 2011 trawl block? it is the parameter in the south with the highest estimated variance

2011 is the first year of the catch shares program which had a dramatic impact on retention, but I think it's likely to have impacted selectivity as well being forced to account for all catch meant that trawlers avoided areas with low quota stocks

having length comps from discards and retained fish in the periods before and after SHOULD be enough to estimate block on both retention and selex in 2011, but regularization may say otherwise
first exploration I would take is removing block from selex, and just estimating change in retention
there's so little trawl in the south in recent years that the sample sizes are probably low and the impact on the model small so little information about that change


![image](https://user-images.githubusercontent.com/4108564/122777657-18859380-d261-11eb-8121-67fcdc86273c.png)

**Comment by iantaylor-NOAA** [comment]
Everything on this list has either been addressed or is unlikely to get addressed this year.
