### ISSUE TITLE
supplementary material for management regulations

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#78]
The text currently says "Summaries of regulatory histories for both federal and state management actions are available as supplementary materials to this stock assessment" but the TOR says 
![image](https://user-images.githubusercontent.com/4108564/122677261-7a2cfb80-d196-11eb-8cf4-7e71bcefc1d0.png)

Do we have this "Supplementary material", do we even need it if we have it, or should we eliminate it from doc/16management.Rmd

**Comment by iantaylor-NOAA** [comment]
From a quick skim of the 2021 Dover assessment, I see only the following few paragraphs on management history and no evidence of supplementary material. Go ahead and cut out that text.
![image](https://user-images.githubusercontent.com/4992918/122677459-325aa400-d197-11eb-8f18-6bacc98ac74b.png)
