### ISSUE TITLE
Need more text, or at least better flowing text

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#81]
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/5937da77a245fa6fa706a2f01c6f5333291d90c7/doc/16management.Rmd#L61

@iantaylor-NOAA, if you have time can you edit this paragraph in the introduction about sampling history?

**Comment by iantaylor-NOAA** [comment]
added in df0c8f0
