### ISSUE TITLE
Add selectivity to the master doc files

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#82]
Bring in this text on [selectivity](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/5937da77a245fa6fa706a2f01c6f5333291d90c7/doc/selectivity.Rmd).

**Comment by iantaylor-NOAA** [comment]
Added in commit 0a1d510f7a1b2ac1332ee8f694f3a028999ba9c6.
