### ISSUE TITLE
corrections list for document

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#84]
@kellijohnson-NOAA, nice work getting the the internal review doc uploaded! Ling STAT.
Files are on Google Drive [here](https://drive.google.com/drive/folders/10O1RCUJhNKImXZThwmu9hc8bpqdhVIvE ), which should be accessible to us all as well as the internal reviewers, but not yet public. Lurkers are welcome on the repository but will have to wait until June 28 to see a full draft document.

I feel bad immediately creating a list of changes to make, but they are mostly for sections that I contributed to and will help me make sure to fix them without taking the time to do so now. Feel free to edit this comment to add more or create separate issues.

- [x] 2.1.8 Discard rates: add description of resulting rates (Ian)
- [x] 2.2.1.3 NWFSC Hook and Line Survey: 
   - [x] remove note about Harms and 
   - [x] include write-up from Tanya Rodgers
- [x] 2.2.3.2 AFSC Slope Survey: header repeated (I tried to fix this after seeing #75, but failed), also may require update to `\gls{s-aslope}`
   - [x] There was a duplicate header for HKL comps. f134679 corrected this. 
- [x] 2.3.1 Natural mortality: revise text about standard error as appropriate for the final models (Ian)
- [x] 2.3.5 Growth (length-at-age): provide internally estimated growth curve figure (Ian)
- [x] 2.3.6 Ageing precision and bias: fix two figure references (IT)
- [x] 3.1 Selectivity, retention, and discard mortality: make sure it's not as spaced out in later versions or fix formatting
- [ ] Figure 14 in south (catch-rec-tsrecfinmeanlength.csv) does not have pch characters (triangle and sqaure) like the caption says it does

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA regards the note about Harms for the HKL. I have yet to ask, this slipped my mind. Are we replacing with a writeup from Tanya? Should I still ask Harms about the if the write up is applicable?

**Comment by iantaylor-NOAA** [comment]
I'm happy with the write-up--we can remove the note about Harms. The write-up from Tanya Rodgers would be about the index standardization, not the survey sampling (I don't think). @kellijohnson-NOAA will know better and I will leave it to her to edit the file appropriately (including removing the Harms note).

**Comment by brianlangseth-NOAA** [comment]
Ok. I will email Harms to make sure its appropriate and will make the comment an html comment ()

**Comment by iantaylor-NOAA** [comment]
Only remaining issue is caption for Figure 14 in south: "(catch-rec-tsrecfinmeanlength.csv) does not have pch characters (triangle and square) like the caption says it does". Assigning to @kellijohnson-NOAA.
