### ISSUE TITLE
how to reference the base model?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#88]
@kellijohnson-NOAA, I'm sure you've told me this already, but I just started doc/model-parameters.Rmd in f696979a1dc03468b6565c0aef94831d4ed4350f and realized that I don't know how we reference the base model output. Did you decide we should create a .rda file for each area?

**Comment by kellijohnson-NOAA** [comment]
These are created for us in unfit\lingcod_builddoc with read_model. Then they are automatically loaded when you run bookdown::render. If you want to experiment with having it in your workspace to see what the objects are named you can go to the model folder and you will see 00mod.Rdata. Load this in R. Then you will have an object called `model`. This is the result of `SS_output()`.
