### ISSUE TITLE
broken file path

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#92]
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/ab2b68d229ac0cbd2476f5a27d60271f27da12ad/R/plot_indices.R#L56

The above file path is a full path with ".." appended to the front of it. So (1) the path will not work on someone else's machine if you were to share csv files and (2) it doesn't work on my machine because it looks like ..\C:\stockassessment\lingcod_2021\models\blahblahblah.
I went in and manually changed the csvs for right now to be able to build, but Ian do you have a quick fix for this or should I just enter with a browser and find a solution?

**Comment by iantaylor-NOAA** [comment]
Sorry, I forgot to use `basename()` and then forgot to actually look at the csv file produced. Hopefully now fixed in b192861. Now the filein value looks like `../models/2021.n.015.004_extraSD/custom_plots/index_fits_all_fleets.png`. Please report if that doesn't look right.

**Comment by kellijohnson-NOAA** [comment]
Thanks!
