### ISSUE TITLE
refine .gitignore

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#93]
Posting a comment here to raise awareness and so it doesn't mess anyone up. 
In 97a6d443b3420d81f03aa519031007c3a2463094 I've just added some lines to .gitignore to focus only on the current base model folders and the stuff we want from profiles.

@kellijohnson-NOAA please feel free to change these as you wish and I can always modify my own, uncommitted version as needed to avoid distractions from extra files.

**Comment by kellijohnson-NOAA** [comment]
I am fine Ian with ignoring everything and being very explicit when we want to include something with -f. So, no edits from me.
