### ISSUE TITLE
Receive comments on internal review version

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#97]
Expecting suggestions on [North (1) and South (1)](https://drive.google.com/drive/folders/10O1RCUJhNKImXZThwmu9hc8bpqdhVIvE) from the following individuals with a deadline of **Friday June 25, 2021 1700h**:

- [x] @aliwhitman - part 1
- [x] @aliwhitman - part 2
- [x] @andi-stephens-NOAA 
- [x] @brianlangseth-NOAA
- [x] @iantaylor-NOAA 
- [x] @kellijohnson-NOAA 
- [ ] @melissahaltuch-NOAA
- [ ] @melissamonk-NOAA 
- [ ] @LaurelLam-NOAA 
- [ ] John B.
- [x] Owen H.
- [ ] John F.
- [ ] Devo

Feel free to directly edit the files, and if you are uncertain of a change just ask someone, do a pull request instead of a push, or highlight the text in **bold** by surrounding it with two stars on either side with a `to do` so it looks like this **to do: ...**. Please feel free to check off your name once you are done or if you do not have time to provide edits check your name off right now. I love checking off boxes!

**Comment by iantaylor-NOAA** [comment]
Note that the files are `North(1).pdf` and `South(1).pdf` in this Google Drive folder, uploaded by Kelli late last night / early this morning: https://drive.google.com/drive/folders/10O1RCUJhNKImXZThwmu9hc8bpqdhVIvE

**Comment by andi-stephens-NOAA** [comment]
Bogged down working on SIS stuff.  Let me know if there's anything specific I can help with.

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA What versions do you want us to look over: North or North (1), South or South (1)?

**Comment by brianlangseth-NOAA** [comment]
Nevermind, I see @iantaylor-NOAA note above.

**Comment by brianlangseth-NOAA** [comment]
Perhaps @andi-stephens-NOAA resolved but note for later fixing: there are two Jagielo 1994 references, and two Haltuch et al. 2018 citations.

**Comment by andi-stephens-NOAA** [comment]
> Perhaps @andi-stephens-NOAA resolved but note for later fixing:
> 
> * [ ]  there are two Jagielo 1994 references, and two Haltuch et al. 2018 citations.
> 
> Other suggestions I could not find out how to change:
> 
> * [ ]  Figure 14 in south (catch-rec-tsrecfinmeanlength.csv) does not have pch characters (triangle and sqaure) like the caption says it does

The two Jagielo refs I think are due to a conflict between sa4ss.bib and Lingcod.bib

The two Haltuch refs are in sa4ss.bib, I think.

I'll fix those.

**Comment by andi-stephens-NOAA** [comment]
> > Perhaps @andi-stephens-NOAA resolved but note for later fixing:
> > 
> > * [ ]   there are two Jagielo 1994 references, and two Haltuch et al. 2018 citations.
> > 
> > Other suggestions I could not find out how to change:
> > 
> > * [ ]   Figure 14 in south (catch-rec-tsrecfinmeanlength.csv) does not have pch characters (triangle and sqaure) like the caption says it does
> 
> The two Jagielo refs I think are due to a conflict between sa4ss.bib and Lingcod.bib
> 
> The two Haltuch refs are in sa4ss.bib, I think.
> 
> I'll fix those.

Actually, that begs the question:  Kelli, you wanted the Lingcod.bib file to have all the Lingcod refs, but you're pulling in the sa4ss.bib.  Should the duplicates be removed from the Lingcod file, or the sa4ss file?

**Comment by kellijohnson-NOAA** [comment]
duplicates should be removed from lingcod.bib

**Comment by andi-stephens-NOAA** [comment]
Will do.

**Comment by andi-stephens-NOAA** [comment]
Actually, changing those right now would require changes to a lot of Rmd files in which the Lingcod.bib version is referenced.  It's probably better to leave those for now, since everyone's working on the document at once.

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA the table issue for sample sizes is because there is still an & sign in the south tables and it won't build with them so i quickly just copied them over with the north until i can fix it.

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA Thank you for the explanation. 3ccaea9 switches H&L to HKL , so no need for you to do.
