### ISSUE TITLE
Re-tune the north model recruitment bias adjustment and early/main split

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#99]
Bias adjustment settings in the north model needed an update as the inclusion of fishery-dependent CAAL data proved to be informative about recdevs in the 1980s so the bias adjustment settings will benefit from re-tuning (first fig below). The south model does not have this issue as the change in age compositions from previous runs have had less impact (noted in #87).

I already ran a model with the re-tuned bias adjustment and it doesn't have a big impact but @kellijohnson-NOAA pointed out that it's a better model so we should go ahead and switch. However, I didn't think to shift the early/main split so will do that now before uploading (starting main recdevs in 1960 instead of 1965--blue to black transition in 2nd fig below). I expect the early/main change to be even less consequential than the tuning but again seems like the right thing to do and there's time to adapt to the change. I'll upload model files shortly.

![image](https://user-images.githubusercontent.com/4992918/123317978-8d680000-d4e3-11eb-9a6c-1a418f41207e.png)

![image](https://user-images.githubusercontent.com/4992918/123318203-d1f39b80-d4e3-11eb-9981-e5ac919b26db.png)

**Comment by kellijohnson-NOAA** [comment]
- [ ] upload tuned
- [ ] run tuned with hessian
- [ ] run jitter @kellijohnson-NOAA 
- [ ] run profiles and retro @kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment]
Jitter of 2021.n.015.004 was fine for 47 runs, so I am not expecting any problems with a deviant of this model.
![Jitter_0 05](https://user-images.githubusercontent.com/4108564/123321101-69a6b900-d4e7-11eb-9595-380787a32b37.png)

**Comment by iantaylor-NOAA** [comment]
Model input files for 2021.n.016.001 uploaded in 00a19e8 may be good enough to start diagnostics. I'll upload output files after eating lunch.

**Comment by kellijohnson-NOAA** [comment]
profiles, jitter, and retro are running on remote machine

**Comment by kellijohnson-NOAA** [comment]
76 jitters are done, so I am confident they will be done by tomorrow.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA where should I upload the files for a model with a lower NLL? 30/100 converged on a solution with NLL of 5061.09, whereas the base model was 5061.13. Though there are 7 parameters on the bounds for both models.
![Jitter_0 05](https://user-images.githubusercontent.com/4108564/123472017-75f44a00-d5ab-11eb-8e54-8d7963473428.png)

**Comment by kellijohnson-NOAA** [comment]
Frequency of parameters on the bounds over 100 jitter runs

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/KELLI~1.JOH/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/KELLI~1.JOH/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Var1 | Freq
-- | --
L_at_Amin_Fem_GP_1 | 1
L_at_Amin_Mal_GP_1 | 5
Q_extraSD_1_Comm_Trawl(1) | 6
Q_extraSD_2_Comm_Fix(2) | 78
Q_extraSD_3_Rec_WA(3) | 4
Q_extraSD_4_Rec_OR(4) | 72
Q_extraSD_5_Rec_CA(5) | 6
Q_extraSD_6_Surv_TRI(6) | 9
Retain_L_infl_1_Comm_Trawl(1)_BLK2repl_1998 | 67
Retain_L_infl_1_Comm_Trawl(1)_BLK2repl_2007 | 64
Retain_L_width_1_Comm_Trawl(1)_BLK3repl_1998 | 14
Retain_L_width_1_Comm_Trawl(1)_BLK3repl_2011 | 17
Retain_L_width_2_Comm_Fix(2)_BLK5repl_1998 | 15
Retain_L_width_2_Comm_Fix(2)_BLK5repl_2011 | 19
Size_DblN_descend_se_1_Comm_Trawl(1)_BLK1repl_1993 | 10
Size_DblN_descend_se_3_Rec_WA(3)_BLK6repl_1987 | 1
Size_DblN_descend_se_4_Rec_OR(4)_BLK7repl_1995 | 1
Size_DblN_descend_se_4_Rec_OR(4)_BLK7repl_1998 | 65
Size_DblN_peak_1_Comm_Trawl(1)_BLK1repl_1993 | 57
Size_DblN_peak_3_Rec_WA(3)_BLK6repl_2011 | 1
Size_DblN_peak_6_Surv_TRI(6) | 64
SR_LN(R0) | 4



</body>

</html>

**Comment by iantaylor-NOAA** [comment]
Difference in NLL is pretty small, but good to figure out and decide what to do from there.
Could you add a row to models/README.md and call it something like 
2021.n.016.002_jitter_sample and add explanation and reference this issue?
If it's hard to tweak the starting values or other aspects of the model to reliably return to this lower NLL solution, then it might be necessary to look at a larger set, but I'm guessing one example will be enough.

**Comment by iantaylor-NOAA** [comment]
I just added a 2021.n.018.001 which is very similar to the previous north model but removes the warnings about parameters on bounds by fixing extraSD parameters for the FG and OR rec indices which were hitting 0 (as noted in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/76#issue-925412135), and widening the bounds on a few parameters. The model results aren't much different, but with the workflow we have, there's no big downside to re-running the diagnostics on this new model.

**Comment by iantaylor-NOAA** [comment]
I'm trying a few more refinements to the north model even though we're short on time.

There remain a 3 selectivity parameters on bounds that I didn't deal with before:
```
mod.2021.n.018.001$estimated_non_dev_parameters %>% dplyr::filter(Status != "OK") %>% dplyr::select(Value, Min, Max)
                                                       Value Min Max
Size_DblN_descend_se_1_Comm_Trawl(1)_BLK1repl_1993 -0.945975  -1  15
Retain_L_infl_1_Comm_Trawl(1)_BLK2repl_1998        99.997900  30 100
Size_DblN_descend_se_4_Rec_OR(4)_BLK7repl_1998     14.891600  -1  15
```
We could fix these parameters at their bounds, which is fine if the bound is natural, like the descending slope wanting to be fully asymptotic as in the Rec_OR selectivity, but less satisfying for something like the Comm_Trawl descending selectivity in for the period 1993 to 1997 (yellow line in the upper left plot below). The 1993 block was chosen to match a change in mesh size, which is reasonable except that the ascending slope and peak don't change much in that year, which are the parameters you would expect to change with a larger mesh allowing small fish to escape. A steeper dome-shaped pattern doesn't match the mesh change, so I've just removed the block starting in 1993. I've likewise removed a block on Comm_Trawl retention in 2007 because the two green lines in the lower left plot below aren't that different and the peak parameter for the lime-green line is the one hitting the upper bound at 100. The data which are informing that parameter seem to be the discard length comps which may be given too much emphasis because our data weighting options apply equally to retained and discard comps (note here: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/93).

I'll report on the model results in a bit.
![selectivity_comm](https://user-images.githubusercontent.com/4992918/123500783-5c77f000-d5f5-11eb-8343-0ed44a8b4da2.png)

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, as we agreed via chat but recording here on github, the North model 2021.n.020.001 is the one to go with, where the three on-bound parameters noted above (https://github.com/iantaylor-NOAA/Lingcod_2021/issues/99#issuecomment-868946012) are fixed at the bounds. This results in a model that is almost identical to 2021.n.018.001 (NLL differs by only 0.01), but has a lower maximum gradient (8.9e-05) and will presumably perform better in the jitter analysis.

Grouping selectivity blocks resulted in a less-good fit to various data sources and didn't solve the problem.

The figures and tables for the first two sensitivity groups for this model were added in d340ddc4283a5ddf4a4d65f747711a1540f478f4 and the r4ss plots were uploaded to https://iantaylor-noaa.github.io/Lingcod_2021/North/, in 420ecf5f836354d39b4df777df7dccccf06880de (#95). This means fetching the repo will be slower for those commit because all those figures changed and the model output files were added.

**Comment by iantaylor-NOAA** [comment]
Diagnostics seem alright for 2021.n.020.001 model so far, closing this.
